"use strict";
let IH=2463534242,HJ=()=>{let x=IH;x^=x<<13;x^=x>>>17;x^=x<<5;IH=x;return x;},G=f=>function(){return f(this);},M=f=>function(p1){return f(this,p1);},Be=f=>function(p1,p2){return f(this,p1,p2);},IZ=f=>(args,callback)=>{if(!args){args=[];}let javaArgs=N(Cy(),args.length);for(let i=0;i<args.length;++i){javaArgs.data[i]=Cs(args[i]);}K0(()=>{f.call(null,javaArgs);},callback);},GX=target=>target.$clinit=()=>{},Ns=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls.$meta&&cls.$meta.item){++arrayDegree;cls=cls.$meta.item;}let clsName
="";if(cls.$meta.primitive){clsName=cls.$meta.name;}else {clsName=cls.$meta?cls.$meta.name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName+="[]";}return clsName;},H=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0){superclass=Cy();}return function(){superclass.call(this);};},R=cls=>ES(cls),Cy=()=>F,Nx=()=>{return {$array:null,classObject:null,$meta:{supertypes:[],superclass:null}};},El=(name,binaryName)=>{let cls=Nx();cls.$meta.primitive=true;cls.$meta.name=name;cls.$meta.binaryName
=binaryName;cls.$meta.enum=false;cls.$meta.item=null;cls.$meta.simpleName=null;cls.$meta.declaringClass=null;cls.$meta.enclosingClass=null;return cls;},Ho=El("char","C"),GF=El("int","I"),Lo=El("void","V"),B1=(a,b)=>a>b?1:a<b? -1:a===b?0:1,KT=Math.imul||function(a,b){let ah=a>>>16&0xFFFF;let al=a&0xFFFF;let bh=b>>>16&0xFFFF;let bl=b&0xFFFF;return al*bl+(ah*bl+al*bh<<16>>>0)|0;},Fa=(a,b)=>(a>>>0)/(b>>>0)>>>0,Ny=(a,b)=>(a>>>0)%(b>>>0)>>>0,EA=(a,b)=>{a>>>=0;b>>>=0;return a<b? -1:a>b?1:0;},Ec=BigInt(0),Ed=val=>BigInt.asIntN(64,
BigInt(val|0)),Jc=val=>Number(BigInt.asIntN(32,val))|0,Gu=(a,b)=>a!==b,JG=(a,b)=>BigInt.asIntN(64,a+b),GE=a=>BigInt.asIntN(64, -a),LM=(a,b)=>BigInt.asIntN(64,a -b),MT=(a,b)=>BigInt.asIntN(64,a/b),Dz=(a,b)=>BigInt.asIntN(64,a&b),JE=(a,b)=>BigInt.asIntN(64,a|b),KC=(a,b)=>BigInt.asIntN(64,a^b),HT=(a,b)=>BigInt.asIntN(64,a<<BigInt(b&63)),KN=(a,b)=>BigInt.asIntN(64,BigInt.asUintN(64,a)>>BigInt(b&63)),N=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (Cx(cls))(data);},Ds=(cls,data)=>new (Cx(cls))(data),K6
=(cls,sz)=>new (Cx(cls))(new Array(sz)),Df=sz=>new L_(new Uint16Array(sz)),BE=sz=>new Ml(new Int32Array(sz)),Cx=cls=>{let result=cls.$array;if(result===null){function JavaArray(data){(Cy()).call(this);this.data=data;}JavaArray.prototype=Object.create((Cy()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.I
=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (Cx(this.type))(dataCopy);};let name="["+cls.$meta.binaryName;JavaArray.$meta={item:cls,supertypes:[Cy()],primitive:false,superclass:Cy(),name:name,binaryName:name,enum:false,simpleName:null,declaringClass:null,enclosingClass:null};JavaArray.classObject=null;JavaArray.$array=null;result=JavaArray;cls.$array
=JavaArray;}return result;},Nu=(cls,dimensions)=>{let first=0;for(let i=dimensions.length -1;i>=0;i=i -1|0){if(dimensions[i]===0){first=i;break;}}if(first>0){for(let i=0;i<first;i=i+1|0){cls=Cx(cls);}if(first===dimensions.length -1){return N(cls,dimensions[first]);}}let arrays=new Array(K9(dimensions,first));let firstDim=dimensions[first]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=N(cls,firstDim);}return Kh(cls,arrays,dimensions,first);},K9=(dimensions,start)=>{let val=dimensions[start+1]|0;for(let i=
start+2;i<dimensions.length;i=i+1|0){val=val*(dimensions[i]|0)|0;if(val===0){break;}}return val;},Kh=(cls,arrays,dimensions,start)=>{let limit=arrays.length;for(let i=start+1|0;i<dimensions.length;i=i+1|0){cls=Cx(cls);let dim=dimensions[i];let index=0;let packedIndex=0;while(index<limit){let arr=K6(cls,dim);for(let j=0;j<dim;j=j+1|0){arr.data[j]=arrays[index];index=index+1|0;}arrays[packedIndex]=arr;packedIndex=packedIndex+1|0;}limit=packedIndex;}return arrays[0];},Fo,JL=strings=>{Mu();Fo=new Array(strings.length);for
(let i=0;i<strings.length;++i){Fo[i]=Gv(Cs(strings[i]));}},E=index=>Fo[index],G_=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},Cs=str=>str===null?null:LI(str),D9=str=>str===null?null:str.d9,Mu=()=>(()=>{})();
let Gv;
{Gv=str=>str;}let DK=(obj,cls)=>obj instanceof Cy()&&!!obj.constructor.$meta&&Ei(obj.constructor,cls),Ei=(from,to)=>{if(from===to){return true;}let map=from.$meta.assignableCache;if(typeof map==='undefined'){map=new Map();from.$meta.assignableCache=map;}let cachedResult=map.get(to);if(typeof cachedResult!=='undefined'){return cachedResult;}if(to.$meta.item!==null){let result=from.$meta.item!==null&&Ei(from.$meta.item,to.$meta.item);map.set(to,result);return result;}let supertypes=from.$meta.supertypes;for(let i
=0;i<supertypes.length;i=i+1|0){if(Ei(supertypes[i],to)){map.set(to,true);return true;}}map.set(to,false);return false;},S=ex=>{throw Kb(ex);},CP=Symbol("javaException"),Kb=ex=>{if(!ex.$jsException){GY(ex);}return ex.$jsException;},GY=ex=>{let javaCause=NJ(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;let err=new Cq("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[CP]=ex;ex.$jsException
=err;Ir(err,ex);},Ir=(err,ex)=>{if(typeof Jg==="function"&&err.stack){let stack=Jg(err.stack);let javaStack=N(JC(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=L9(Cs(element.className),Cs(element.methodName),Cs(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){J2(ex,javaStack);}}},Cq;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");Cq=function Cq(message,cause){let self=Reflect.construct(Error,[void 0,cause],Cq);Object.setPrototypeOf(self,Cq.prototype);self[defaultMessage]=message;return self;}
;Cq.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:Cq},message:{get(){try {let javaException=this[CP];if(typeof javaException==='object'){let javaMessage=Li(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {Cq=Error;}let Lp=e=>e instanceof Error&&typeof e[CP]==='object'?e[CP]:null,Bb=err=>
{let ex=err[CP];if(!ex){ex=Ly(Cs("(JavaScript) "+err.toString()));err[CP]=ex;ex.$jsException=err;Ir(err,ex);}return ex;},Ly=message=>FP(message),Li=t=>NF(t),NJ=t=>NM(t),JC=()=>Cy(),L9=(className,methodName,fileName,lineNumber)=>{{return null;}},J2=(e,stack)=>{},Mb=outputFunction=>{let buffer="";return msg=>{let index=0;while(true){let next=msg.indexOf('\n',index);if(next<0){break;}outputFunction(buffer+msg.substring(index,next));buffer="";index=next+1;}buffer+=msg.substring(index);};},Kf=typeof $rt_putStderrCustom
==="function"?$rt_putStderrCustom:typeof console==="object"?Mb(msg=>console.error(msg)):()=>{},Gj=null,Ki=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}Gj=packages;},DE=data=>{let packages=Gj;let i=0;while(i<data.length){let cls=data[i++];cls.$meta={};let m=cls.$meta;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex=data[i++];if
(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.superclass=superclass!==0?superclass:null;m.supertypes=data[i++];if(m.superclass){m.supertypes.push(m.superclass);cls.prototype=Object.create(m.superclass.prototype);}else {cls.prototype={};}let flags=data[i++];m.enum=(flags&8)!==0;m.flags=flags;m.primitive=false;m.item=null;cls.prototype.constructor=cls;cls.classObject=null;m.accessLevel=data[i++];let innerClassInfo=data[i++];if(innerClassInfo===
0){m.simpleName=null;m.declaringClass=null;m.enclosingClass=null;}else {let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit=data[i++];cls.$clinit=clinit!==0?clinit:function(){};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func
=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}cls.$array=null;}},K0=(runner,callback)=>{let result;try {result=runner();}catch(e){result=e;}if(typeof callback!=='undefined'){callback(result);}else if(result instanceof Error){throw result;}};
function F(){this.$id$=0;}
let CY=a=>{return ES(a.constructor);},Np=a=>{return Eo(a);},Bg=(a,b)=>{return a!==b?0:1;},Mh=a=>{let b,c,d,e,f,g,h,i,j;b=Eo(a);if(!b)c=E(0);else{if(!b)d=32;else{e=0;d=b>>>16|0;if(d)e=16;else d=b;f=d>>>8|0;if(!f)f=d;else e=e|8;d=f>>>4|0;if(!d)d=f;else e=e|4;f=d>>>2|0;if(!f)f=d;else e=e|2;if(f>>>1|0)e=e|1;d=(32-e|0)-1|0;}d=(((32-d|0)+4|0)-1|0)/4|0;g=Df(d);h=g.data;e=(d-1|0)*4|0;f=0;while(e>=0){i=f+1|0;h[f]=FL((b>>>e|0)&15,16);e=e-4|0;f=i;}c=Jd(g);}j=U();I(I(j,E(1)),c);return T(j);},Eo=a=>{let b;b=a;if(!b.$id$)b.$id$
=HJ();return a.$id$;},NX=a=>{let b,c,d;if(!DK(a,Cm)&&a.constructor.$meta.item===null){b=new Ge;Y(b);S(b);}b=Jy(a);c=b;d=HJ();c.$id$=d;return b;},GL=H(0),Gg=H(0);
function GV(){let a=this;F.call(a);a.fU=null;a.eR=null;}
let ES=b=>{let c;if(b===null)return null;c=b.classObject;if(c===null){c=new GV;c.eR=b;b.classObject=c;}return c;},Gn=a=>{return ES(a.eR.$meta.item);},M8=H(),Md=H(),Jy=b=>{let copy=new b.constructor();for(let field in b){if(b.hasOwnProperty(field)){copy[field]=b[field];}}return copy;},Hd=(b,c)=>{let d,e;if(b===c)return 1;d=b.$meta.supertypes;e=0;while(e<d.length){if(Hd(d[e],c))return 1;e=e+1|0;}return 0;},EP=b=>{let c='$$enumConstants$$';C4[c]=KD;Cu[c]=Go;EP=cls=>{if(!cls.hasOwnProperty(c)){return null;}if(typeof cls[c]
==="function"){cls[c]=cls[c]();}return cls[c];};return EP(b);};
function FE(){let a=this;F.call(a);a.gn=null;a.gj=null;a.g2=0;a.he=0;a.h7=null;}
let NS=a=>{return a;},G3=a=>{GY(a);},NF=a=>{return a.gn;},NM=a=>{let b;b=a.gj;if(b===a)b=null;return b;},Cz=H(FE),Y=a=>{G3(a);a.g2=1;a.he=1;},NP=()=>{let a=new Cz();Y(a);return a;},Bv=H(Cz),Ci=(a,b)=>{G3(a);a.g2=1;a.he=1;a.gn=b;},FP=a=>{let b=new Bv();Ci(b,a);return b;},C5=H(Bv),BV=H(0),C2=H(0),Fj=H(0),BX=H(),Lm=null,JT=null,Jz=null,Kk=(a,b)=>{a.d9=G_(b.data,0,b.data.length);},Jd=a=>{let b=new BX();Kk(b,a);return b;},KQ=(a,b)=>{a.d9=b;},LI=a=>{let b=new BX();KQ(b,a);return b;},E0=(a,b)=>{let c;if(b>=0&&b<a.d9.length)return a.d9.charCodeAt(b);c
=new Fr;Y(c);S(c);},KW=()=>{let b;Lm=Df(0);b=new BX;b.d9="";JT=b;Jz=new H$;},FH=H();
function DF(){FH.call(this);this.e0=0;}
let JO=null,Eb=null,IU=(a,b)=>{a.e0=b;},GT=a=>{let b=new DF();IU(b,a);return b;},DZ=b=>{return (G6(LD(20),b,10)).g();},B2=b=>{let c,d;if(b>=(-128)&&b<=127){a:{if(Eb===null){Eb=N(DF,256);c=0;while(true){d=Eb.data;if(c>=d.length)break a;d[c]=GT(c-128|0);c=c+1|0;}}}return Eb.data[b+128|0];}return GT(b);},Ji=a=>{return a.e0;},MC=(a,b)=>{if(a===b)return 1;return b instanceof DF&&b.e0==a.e0?1:0;},Jw=()=>{JO=R(GF);};
function DR(){let a=this;F.call(a);a.d_=null;a.ec=0;}
let GQ=(a,b)=>{a.d_=Df(b);},LD=a=>{let b=new DR();GQ(b,a);return b;},G6=(a,b,c)=>{return LV(a,a.ec,b,c);},LV=(a,b,c,d)=>{let e,f,g,h,i,j,k;e=1;if(c<0){e=0;c= -c|0;}a:{if(EA(c,d)<0){if(e)DO(a,b,b+1|0);else{DO(a,b,b+2|0);f=a.d_.data;g=b+1|0;f[b]=45;b=g;}a.d_.data[b]=FL(c,d);}else{h=1;i=1;j=Fa((-1),d);b:{while(true){k=KT(h,d);if(EA(k,c)>0){k=h;break b;}i=i+1|0;if(EA(k,j)>0)break;h=k;}}if(!e)i=i+1|0;DO(a,b,b+i|0);if(e)e=b;else{f=a.d_.data;e=b+1|0;f[b]=45;}while(true){if(!k)break a;f=a.d_.data;b=e+1|0;f[e]=FL(Fa(c,
k),d);c=Ny(c,k);k=Fa(k,d);e=b;}}}return a;},Fc=(a,b)=>{let c,d,e,f,g;c=a.d_.data.length;if(c>=b)return;d=c>=1073741823?2147483647:D0(b,D0(c*2|0,5));e=a.d_.data;f=Df(d);g=f.data;b=DN(d,e.length);c=0;while(c<b){g[c]=e[c];c=c+1|0;}a.d_=f;},T=a=>{let b,c,d,e,f;b=new BX;c=a.d_;d=c.data;e=a.ec;f=d.length;if(e>=0&&e<=(f-0|0)){b.d9=G_(c.data,0,e);return b;}b=new BN;Y(b);S(b);},DO=(a,b,c)=>{let d,e,f,g;d=a.ec;e=d-b|0;a.q((d+c|0)-b|0);f=e-1|0;while(f>=0){g=a.d_.data;g[c+f|0]=g[b+f|0];f=f+(-1)|0;}a.ec=a.ec+(c-b|0)|0;},E4
=H(0),Gp=H(DR),Mg=a=>{GQ(a,16);},U=()=>{let a=new Gp();Mg(a);return a;},I=(a,b)=>{let c,d;c=a.ec;d=a;b=b===null?E(2):b;IF(d,c,b);return a;},L=(a,b)=>{let c;c=a.ec;IF(a,c,b);return a;},Bh=(a,b)=>{G6(a,b,10);return a;},B6=(a,b)=>{let c,d;c=a.ec;d=a;DO(d,c,c+1|0);d.d_.data[c]=b;return a;},L4=a=>{return T(a);},M_=(a,b)=>{Fc(a,b);},IF=(a,b,c)=>{let d,e,f,g;if(b>=0&&b<=a.ec){a:{if(c===null)c=E(2);else if(c.d9.length?0:1)break a;d=a.ec+c.d9.length|0;Fc(a,d);e=a.ec-1|0;while(e>=b){a.d_.data[e+c.d9.length|0]=a.d_.data[e];e
=e+(-1)|0;}a.ec=a.ec+c.d9.length|0;d=0;while(d<c.d9.length){f=a.d_.data;g=b+1|0;f[b]=E0(c,d);d=d+1|0;b=g;}}return a;}c=new Fr;Y(c);S(c);},MW=H(),Nk=H(),JB=H(),IJ=H(),C$=()=>{C$=GX(IJ);LT();},DW=b=>{C$();return (b+0.05)*10.0|0;},K1=b=>{C$();},MO=b=>{if(typeof globalThis.seRatingProgress==='function')globalThis.seRatingProgress(b);},D=b=>{let c,d,e,f,g,h,$$je;C$();b=Cs(b);c=Cg();d=0;while(d<81){e=E0(b,d);if(e>=49&&e<=57){f=d%9|0;g=d/9|0;c.en.data[g].data[f].d3=e-48|0;}d=d+1|0;}a:{h=HN(c);GS(h);if(b.d9.length>=
810){f=0;while(true){if(f>=81)break a;g=1;while(g<=9){if(E0(b,((81+(f*9|0)|0)+g|0)-1|0)==48)Dn(Bf(c,f%9|0,f/9|0),g);g=g+1|0;}f=f+1|0;}}}b=new IP;b.f1=0;h.hh=b;b:{try{KY(h);break b;}catch($$e){$$je=Bb($$e);if($$je instanceof DM){}else{throw $$e;}}h.eQ=0.0;h.fn=0.0;h.ea=0.0;}d=DW(h.ea);e=DW(h.fn);f=DW(h.eQ);b=U();Bh(B6(Bh(B6(Bh(b,d),47),e),47),f);return D9(T(b));},LT=()=>{KW();Jw();KG();No();Kg();J5();Nf();Jq();},NE=H(),C3=H(0),H$=H(),HX=H(),JN=null,Mo=null,FL=(b,c)=>{if(c>=2&&c<=36&&b>=0&&b<c)return b<10?(48
+b|0)&65535:((97+b|0)-10|0)&65535;return 0;},KG=()=>{JN=R(Ho);Mo=N(HX,128);},Kj=H(),E5=(b,c)=>{if(b===c)return 1;return b!==null?b.C(c):c!==null?0:1;},DX=b=>{return b!==null?b.D():0;},DG=b=>{if(b!==null)return b;b=new CC;Ci(b,E(3));S(b);},Ni=H();
function E3(){let a=this;F.call(a);a.en=null;a.fs=null;a.fw=null;a.fH=null;a.eB=null;}
let KL=a=>{let b,c,d,e,f,g;b=Nu(BD,[9,9]);c=b.data;a.en=b;a.fs=N(Bu,9);a.fw=N(Br,9);a.fH=N(Bk,9);a.eB=null;d=0;while(d<9){e=0;while(e<9){b=c[d].data;f=new BD;f.d3=0;f.dT=new Z;f.e6=a;f.dY=e;f.dX=d;b[e]=f;e=e+1|0;}d=d+1|0;}g=0;while(g<9){b=a.fs.data;f=new Bu;f.gJ=a;En(f,a);f.e4=g;b[g]=f;b=a.fw.data;f=new Br;f.gU=a;En(f,a);f.fk=g;b[g]=f;b=a.fH.data;f=new Bk;e=g/3|0;d=g%3|0;f.gM=a;En(f,a);f.fd=e;f.fm=d;b[g]=f;g=g+1|0;}},Cg=()=>{let a=new E3();KL(a);return a;},Bf=(a,b,c)=>{return a.en.data[c].data[b];},BJ=(a,b)=>
{if(b===R(Bu))return a.fs;if(b!==R(Br))return a.fH;return a.fw;},GJ=(a,b,c)=>{return a.en.data[c].data[b].d3;},BQ=(a,b,c,d)=>{if(Bg(b,R(Bu)))return a.fs.data[d];if(Bg(b,R(Br)))return a.fw.data[c];return a.fH.data[((d/3|0)*3|0)+(c/3|0)|0];},DJ=(a,b,c)=>{return BQ(a,b,c.dY,c.dX);},BM=a=>{let b,c;if(a.eB===null){b=Cf(3);a.eB=b;b.G(R(Bk));a.eB.G(R(Bu));a.eB.G(R(Br));b=a.eB;DG(b);c=new F6;c.f8=b;a.eB=c;}return a.eB;},Bx=(a,b)=>{let c,d,e,f;c=0;while(c<9){d=0;while(d<9){e=a.en.data[c].data[d];f=b.en.data[c].data[d];f.d3
=e.d3;f.dT=Bs(e.dT);d=d+1|0;}c=c+1|0;}},D2=(a,b)=>{let c,d,e,f,g;if(!(b instanceof E3))return 0;c=b;d=0;while(d<9){e=0;while(e<9){f=Bf(a,e,d);g=Bf(c,e,d);if(f.d3!=g.d3)return 0;if(!Fe(f.dT,g.dT))return 0;e=e+1|0;}d=d+1|0;}return 1;};
function GZ(){let a=this;F.call(a);a.ea=0.0;a.fn=0.0;a.eQ=0.0;a.gP=0;a.d$=null;a.e3=null;a.d6=null;a.hX=null;a.f7=null;a.eO=null;a.ha=null;a.fX=null;a.fT=null;a.hS=0;a.hh=null;}
let Dt=(a,b,c,d)=>{if(G4(Hy(Ek()),b))J(c,d);},Bm=(a,b,c,d)=>{if(G4(Hy(Ek()),b))J(c,d);},Ja=(a,b)=>{let c,d;a.hS=0;a.d$=b;c=V();a.e3=c;Dt(a,Fi,c,new FW);Dt(a,Ff,a.e3,FZ(1));Dt(a,EZ,a.e3,CZ(2,1));Dt(a,Eg,a.e3,new FY);Dt(a,Fl,a.e3,CZ(3,1));b=V();a.d6=b;Bm(a,FQ,b,FZ(0));Bm(a,Fn,a.d6,DD(2));Bm(a,Et,a.d6,DU(2));Bm(a,Fh,a.d6,CZ(2,0));Bm(a,FI,a.d6,DD(3));Bm(a,Ez,a.d6,DU(3));Bm(a,EC,a.d6,CZ(3,0));Bm(a,EO,a.d6,H2(0));Bm(a,F1,a.d6,H2(1));b=EW;c=a.d6;d=new IG;d.f$=Cg();d.ge=null;Bm(a,b,c,d);Bm(a,FM,a.d6,DD(4));Bm(a,FN,
a.d6,DU(4));Bm(a,EH,a.d6,CZ(4,0));b=FA;c=a.d6;d=new Hq;d.eX=Cg();Bm(a,b,c,d);b=Fb;c=a.d6;d=new Hp;HP(d,2);Bm(a,b,c,d);b=V();a.eO=b;Bm(a,EV,b,BR(0,0,0,0));Bm(a,EX,a.eO,KM(3));Bm(a,Fd,a.eO,BR(0,1,1,0));Bm(a,EI,a.eO,BR(1,0,0,0));Bm(a,Fk,a.eO,BR(1,1,0,0));b=V();a.ha=b;Bm(a,Fz,b,BR(1,1,0,1));b=V();a.hX=b;c=new G2;J(b,c);b=V();a.f7=b;c=new Ht;J(b,c);b=a.f7;c=new Ga;J(b,c);b=a.f7;c=new Ih;c.el=Cg();c.e$=Cg();c.gv=0;J(b,c);b=V();a.fX=b;Bm(a,Dk,b,BR(1,1,0,2));Bm(a,Dk,a.fX,BR(1,1,0,3));b=V();a.fT=b;Bm(a,Dk,b,BR(1,1,0,
4));Bm(a,Dk,a.fT,BR(1,1,0,5));},HN=a=>{let b=new GZ();Ja(b,a);return b;},FT=(a,b)=>{let c,d,e,f,g,h,i,j;c=(BJ(a.d$,b)).data;d=c.length;e=0;while(e<d){f=c[e];g=0;while(g<9){a:{h=f.S(g);if(!HK(h)){i=h.d3;j=0;while(true){if(j>=9)break a;Dn(f.S(j),i);j=j+1|0;}}}g=g+1|0;}e=e+1|0;}},GS=a=>{let b,c,d,e;b=0;while(b<9){c=0;while(c<9){a:{d=Bf(a.d$,c,b);if(!d.d3){e=1;while(true){if(e>9)break a;CS(d.dT,e,1);e=e+1|0;}}}c=c+1|0;}b=b+1|0;}b=0;while(b<9){c=0;while(c<9){d=Bf(a.d$,c,b);if(d.d3)GI(d);c=c+1|0;}b=b+1|0;}FT(a,R(Bk));FT(a,
R(Bu));FT(a,R(Br));},Mw=a=>{let b,c;b=0;while(b<9){c=0;while(c<9){if(!GJ(a.d$,c,b))return 0;c=c+1|0;}b=b+1|0;}return 1;},KY=a=>{let b,c,d,e,f,g,$$je;b=Cg();Bx(a.d$,b);a:{try{a.ea=(-Infinity);a.fn=0.0;a.eQ=0.0;}catch($$e){$$je=Bb($$e);c=$$je;break a;}b:{c:{d:{e:while(true){try{if(Mw(a))break b;c=Ii();}catch($$e){$$je=Bb($$e);c=$$je;break a;}f:{g:{try{d=O(a.e3);}catch($$e){$$je=Bb($$e);if($$je instanceof BF){break g;}else{c=$$je;break a;}}e=d;while(true){try{if(!P(e))break;(Q(e)).bd(a.d$,c);continue;}catch($$e)
{$$je=Bb($$e);if($$je instanceof BF){break g;}else{c=$$je;break a;}}}try{d=O(a.d6);}catch($$e){$$je=Bb($$e);if($$je instanceof BF){break g;}else{c=$$je;break a;}}e=d;while(true){try{if(!P(e))break;(Q(e)).bd(a.d$,c);continue;}catch($$e){$$je=Bb($$e);if($$je instanceof BF){break g;}else{c=$$je;break a;}}}try{d=O(a.eO);}catch($$e){$$je=Bb($$e);if($$je instanceof BF){break g;}else{c=$$je;break a;}}e=d;while(true){try{if(!P(e))break;(Q(e)).bd(a.d$,c);continue;}catch($$e){$$je=Bb($$e);if($$je instanceof BF){break g;}
else{c=$$je;break a;}}}try{d=O(a.ha);}catch($$e){$$je=Bb($$e);if($$je instanceof BF){break g;}else{c=$$je;break a;}}e=d;while(true){try{if(!P(e))break;(Q(e)).bd(a.d$,c);continue;}catch($$e){$$je=Bb($$e);if($$je instanceof BF){break g;}else{c=$$je;break a;}}}try{d=O(a.fX);}catch($$e){$$je=Bb($$e);if($$je instanceof BF){break g;}else{c=$$je;break a;}}e=d;while(true){try{if(!P(e))break;(Q(e)).bd(a.d$,c);continue;}catch($$e){$$je=Bb($$e);if($$je instanceof BF){break g;}else{c=$$je;break a;}}}try{d=O(a.fT);}catch
($$e){$$je=Bb($$e);if($$je instanceof BF){break g;}else{c=$$je;break a;}}e=d;while(true){try{if(!P(e))break;(Q(e)).bd(a.d$,c);continue;}catch($$e){$$je=Bb($$e);if($$je instanceof BF){break g;}else{c=$$je;break a;}}}try{break f;}catch($$e){$$je=Bb($$e);c=$$je;break a;}}try{break f;}catch($$e){$$je=Bb($$e);c=$$je;break a;}}try{f=Jo(c);if(f===null)break d;g=f.bf();if(g>a.ea)a.ea=g;f.bg();c=a.hh;if(c!==null){g=a.ea;Kn(c,g);}h:{g=a.fn;if(g!==0.0){if(!a.gP)break h;if(a.ea<=g)break h;else break e;}if(a.eQ===0.0)a.eQ
=a.ea;if(f.bi()!==null){if(a.gP==100&&a.ea>a.eQ)break c;a.fn=a.ea;}}continue;}catch($$e){$$je=Bb($$e);c=$$je;break a;}}try{a.ea=20.0;break b;}catch($$e){$$je=Bb($$e);c=$$je;break a;}}try{a.ea=20.0;break b;}catch($$e){$$je=Bb($$e);c=$$je;break a;}}try{a.ea=20.0;break b;}catch($$e){$$je=Bb($$e);c=$$je;break a;}}Bx(b,a.d$);return;}Bx(b,a.d$);S(c);},HS=H(0);
function IP(){F.call(this);this.f1=0;}
let Kn=(a,b)=>{let c;c=DW(b);if(c>a.f1){a.f1=c;MO(c);}},DM=H(Bv),BN=H(Bv);
function BD(){let a=this;F.call(a);a.e6=null;a.dY=0;a.dX=0;a.d3=0;a.dT=null;}
let HK=a=>{return a.d3?0:1;},E8=(a,b)=>{let c,d,e,f;a.d3=b;Hb(a.dT);c=O(BM(a.e6));while(P(c)){d=Q(c);e=BQ(a.e6,d,a.dY,a.dX);f=0;while(f<9){Dn(e.S(f),b);f=f+1|0;}}},Ct=a=>{return a.dT;},X=(a,b)=>{return Bd(a.dT,b);},Dn=(a,b)=>{CS(a.dT,b,0);},GI=a=>{Hb(a.dT);},BL=a=>{let b,c,d,e,f,g;b=B0();c=O(BM(a.e6));d=b;while(P(c)){e=Q(c);f=BQ(a.e6,e,a.dY,a.dX);g=0;while(g<9){Bq(d,f.S(g));g=g+1|0;}}Cw(d,a);return b;},Fw=(b,c)=>{let d,e;if(!(Ek()).g5){d=(65+b|0)&65535;b=c+1|0;e=U();Bh(B6(e,d),b);return T(e);}c=c+1|0;b=b+1|
0;e=U();Bh(B6(Bh(B6(e,82),c),67),b);return T(e);},Do=a=>{return Fw(a.dY,a.dX);},CF=b=>{let c,d,e,f;b=b.data;c=U();L(c,E(4));d=b.length;if(d>1)L(c,E(5));else L(c,E(6));e=0;while(e<d){if(e>0)L(c,E(7));f=b[e];L(c,Fw(f.dY,f.dX));e=e+1|0;}return T(c);},DI=b=>{let c,d,e,f;c=U();d=0;while(true){e=b.data;if(d>=e.length)break;if(d>0)L(c,E(7));f=e[d];L(c,Fw(f.dY,f.dX));d=d+1|0;}return T(c);};
function B5(){F.call(this);this.hq=null;}
let En=(a,b)=>{a.hq=b;},L7=(a,b)=>{let c;c=0;while(c<9){if((a.S(c)).d3==b)return 1;c=c+1|0;}return 0;},BA=(a,b)=>{let c,d;c=new Z;d=0;while(d<9){if(X(a.S(d),b))Bw(c,d);d=d+1|0;}return c;},NW=(a,b)=>{return BA(a,b);},Dh=a=>{let b,c,d;b=B0();c=0;d=b;while(c<9){Bq(d,a.S(c));c=c+1|0;}return b;},Nq=(a,b)=>{let c;c=Dh(a);b=Dh(b);BT(c,b);return c;},FO=(a,b)=>{return CT(Nq(a,b))?0:1;},D3=a=>{let b,c;b=0;c=0;while(c<9){if(HK(a.S(c)))b=b+1|0;c=c+1|0;}return b;};
function Bu(){let a=this;B5.call(a);a.e4=0;a.gJ=null;}
let Mf=(a,b)=>{return a.gJ.en.data[a.e4].data[b];},Nm=(a,b)=>{return b.dY;},Is=(a,b)=>{let c,d;if(b instanceof Bk){c=b;return (a.e4/3|0)!=c.fd?0:1;}if(b instanceof Br)return 1;if(!(b instanceof Bu))return FO(a,b);d=b;return a.e4!=d.e4?0:1;},K_=a=>{return E(8);};
function Br(){let a=this;B5.call(a);a.fk=0;a.gU=null;}
let Nw=(a,b)=>{return a.gU.en.data[b].data[a.fk];},MB=(a,b)=>{return b.dX;},H8=(a,b)=>{let c,d;if(b instanceof Bk){c=b;return (a.fk/3|0)!=c.fm?0:1;}if(b instanceof Bu)return 1;if(!(b instanceof Br))return FO(a,b);d=b;return a.fk!=d.fk?0:1;},J_=a=>{return E(9);};
function Bk(){let a=this;B5.call(a);a.fd=0;a.fm=0;a.gM=null;}
let MX=(a,b)=>{return a.gM.en.data[(a.fd*3|0)+(b/3|0)|0].data[(a.fm*3|0)+(b%3|0)|0];},L2=(a,b)=>{return ((b.dX%3|0)*3|0)+(b.dY%3|0)|0;},Lz=(a,b)=>{let c;if(b instanceof Bu)return Is(b,a);if(b instanceof Br)return H8(b,a);if(!(b instanceof Bk))return FO(a,b);c=b;return a.fd==c.fd&&a.fm==c.fm?1:0;},Nn=a=>{return E(10);},GM=H(0),Dm=H(0),Cb=H(),Bj=a=>{return a.bx()?0:1;},BI=(a,b)=>{let c;c=a.ba();while(c.bb()){if(E5(c.bc(),b))return 1;}return 0;},Co=(a,b)=>{let c,d,e,f;c=b.data;d=a.bx();e=c.length;if(e<d)b=H5(Gn(CY(b)),
d);else while(d<e){c[d]=null;d=d+1|0;}d=0;f=a.ba();while(f.bb()){c=b.data;e=d+1|0;c[d]=f.bc();d=e;}return b;},ER=(a,b)=>{let c;c=O(b);while(P(c)){if(BI(a,Q(c)))continue;else return 0;}return 1;},BW=(a,b)=>{let c,d;c=0;d=b.ba();while(d.bb()){if(!a.G(d.bc()))continue;c=1;}return c;},BT=(a,b)=>{let c,d;DG(b);c=0;d=a.ba();while(d.bb()){if(!b.J(d.bc())){d.bC();c=1;}}return c;},Dx=H(0),Ex=H(0);
function B3(){Cb.call(this);this.d8=0;}
let CB=(a,b)=>{a.bD(a.bx(),b);return 1;},O=a=>{let b;b=new G9;b.gY=a;b.gQ=a.d8;b.gS=a.bx();b.gD=(-1);return b;},Kz=(a,b,c)=>{c=new DM;Y(c);S(c);},EE=(a,b)=>{let c,d,e;if(!DK(b,Ex))return 0;c=b;b=a;d=b.dV;e=c;if(d!=e.dV)return 0;d=0;while(d<e.dV){if(!E5(Bl(b,d),Bl(e,d)))return 0;d=d+1|0;}return 1;},Cm=H(0),Dp=H(0);
function DV(){let a=this;B3.call(a);a.ed=null;a.dV=0;}
let Ko=a=>{Es(a,10);},V=()=>{let a=new DV();Ko(a);return a;},Es=(a,b)=>{let c;if(b>=0){a.ed=N(F,b);return;}c=new Ce;Y(c);S(c);},Cf=a=>{let b=new DV();Es(b,a);return b;},M1=(a,b)=>{let c,d,e,f;Es(a,b.bx());c=b.ba();d=0;while(true){e=a.ed.data;f=e.length;if(d>=f)break;e[d]=c.bc();d=d+1|0;}a.dV=f;},DY=a=>{let b=new DV();M1(b,a);return b;},G0=(a,b)=>{let c,d,e,f;c=a.ed.data.length;if(c<b){d=c>=1073741823?2147483647:D0(b,D0(c*2|0,5));e=a.ed;f=e.data;e=H5(Gn(CY(e)),d);b=DN(d,f.length);d=0;while(d<b){e.data[d]=f[d];d
=d+1|0;}a.ed=e;}},Bl=(a,b)=>{Eu(a,b);return a.ed.data[b];},E_=a=>{return a.dV;},J=(a,b)=>{let c,d;G0(a,a.dV+1|0);c=a.ed.data;d=a.dV;a.dV=d+1|0;c[d]=b;a.d8=a.d8+1|0;return 1;},Mj=(a,b,c)=>{let d,e,f,g;if(b>=0){d=a.dV;if(b<=d){G0(a,d+1|0);e=a.dV;f=e;while(f>b){g=a.ed.data;g[f]=g[f-1|0];f=f+(-1)|0;}a.ed.data[b]=c;a.dV=e+1|0;a.d8=a.d8+1|0;return;}}c=new BN;Y(c);S(c);},Eu=(a,b)=>{let c;if(b>=0&&b<a.dV)return;c=new BN;Y(c);S(c);},MU=a=>{let b,c;b=1;c=0;while(c<a.dV){b=(31*b|0)+DX(a.ed.data[c])|0;c=c+1|0;}return b;};
function Dw(){let a=this;F.call(a);a.hI=null;a.eN=0;}
let CV=(a,b,c)=>{a.hI=b;a.eN=c;};
function C4(){Dw.call(this);this.hH=null;}
let Fi=null,Ff=null,EZ=null,Eg=null,Fl=null,FQ=null,Fn=null,Et=null,Fh=null,FI=null,Ez=null,EC=null,EO=null,F1=null,EW=null,FM=null,FN=null,EH=null,FA=null,Fb=null,EV=null,EX=null,Fd=null,EI=null,Fk=null,Fz=null,Dk=null,Hj=null,KD=()=>{return Hj.I();},Mz=(a,b,c,d)=>{CV(a,b,c);a.hH=d;},Bi=(a,b,c)=>{let d=new C4();Mz(d,a,b,c);return d;},No=()=>{let b,c,d;Fi=Bi(E(11),0,E(12));Ff=Bi(E(13),1,E(14));EZ=Bi(E(15),2,E(16));Eg=Bi(E(17),3,E(18));Fl=Bi(E(19),4,E(20));FQ=Bi(E(21),5,E(22));Fn=Bi(E(23),6,E(24));Et=Bi(E(25),
7,E(26));Fh=Bi(E(27),8,E(28));FI=Bi(E(29),9,E(30));Ez=Bi(E(31),10,E(31));EC=Bi(E(32),11,E(33));EO=Bi(E(34),12,E(35));F1=Bi(E(36),13,E(37));EW=Bi(E(38),14,E(39));FM=Bi(E(40),15,E(41));FN=Bi(E(42),16,E(42));EH=Bi(E(43),17,E(44));FA=Bi(E(45),18,E(46));Fb=Bi(E(47),19,E(48));EV=Bi(E(49),20,E(50));EX=Bi(E(51),21,E(52));Fd=Bi(E(53),22,E(54));EI=Bi(E(55),23,E(56));Fk=Bi(E(57),24,E(58));Fz=Bi(E(59),25,E(60));b=Bi(E(61),26,E(62));Dk=b;c=N(C4,27);d=c.data;d[0]=Fi;d[1]=Ff;d[2]=EZ;d[3]=Eg;d[4]=Fl;d[5]=FQ;d[6]=Fn;d[7]=Et;d[8]
=Fh;d[9]=FI;d[10]=Ez;d[11]=EC;d[12]=EO;d[13]=F1;d[14]=EW;d[15]=FM;d[16]=FN;d[17]=EH;d[18]=FA;d[19]=Fb;d[20]=EV;d[21]=EX;d[22]=Fd;d[23]=EI;d[24]=Fk;d[25]=Fz;d[26]=b;Hj=c;},Fp=H(0),Ew=H(0),FW=H(),HI=(a,b,c)=>{CL(a,b,R(Bk),c,1);CL(a,b,R(Br),c,1);CL(a,b,R(Bu),c,1);CL(a,b,R(Bk),c,0);CL(a,b,R(Br),c,0);CL(a,b,R(Bu),c,0);},CL=(a,b,c,d,e)=>{let f,g,h,i,j,k,l,m;f=(BJ(b,c)).data;g=f.length;h=0;b=d;while(h<g){i=f[h];j=1;while(j<=9){k=BA(i,j);if(K(k)==1){l=i.S(Ba(k,0));m=D3(i)!=1?0:1;if(m==e){c=new Ip;Hs(c,a,i,l,j);c.gK
=m;FX(b,c);}}j=j+1|0;}h=h+1|0;}},BZ=H(0);
function HY(){F.call(this);this.gi=0;}
let Mt=(a,b)=>{a.gi=b;},FZ=a=>{let b=new HY();Mt(b,a);return b;},Mc=(a,b,c)=>{DA(a,b,R(Bk),R(Br),c);DA(a,b,R(Bk),R(Bu),c);DA(a,b,R(Br),R(Bk),c);DA(a,b,R(Bu),R(Bk),c);},DA=(a,b,c,d,e)=>{let f,g,h,i,j,k,l,m,n,o,p,q,r,s;f=0;while(f<9){g=0;while(g<9){a:{h=(BJ(b,c)).data[f];i=(BJ(b,d)).data[g];if(h.bw(i)){j=Dh(i);k=1;l=j;while(true){if(k>9)break a;m=1;n=BA(h,k);if(K(n)>1){o=0;while(o<9){if(Bd(n,o)&&!BP(l,h.S(o)))m=0;o=o+1|0;}if(m){if(!a.gi){p=Iy(a,h,i,null,k);if(p.bR())e.bO(p);}else{q=0;while(q<9){if(q!=f){j=(BJ(b,
c)).data[q];if(j.bw(i)){n=Dh(i);p=BA(j,k);if(K(p)>1){m=0;r=null;o=0;n=n;while(o<9){if(Bd(p,o)){s=j.S(o);if(!BP(n,s)){m=m+1|0;r=s;}}o=o+1|0;}if(m==1){j=Iy(a,h,i,r,k);if(j.bR())e.bO(j);}}}}q=q+1|0;}}}}k=k+1|0;}}}g=g+1|0;}f=f+1|0;}},Iy=(a,b,c,d,e)=>{let f,g,h,i,j,k,l,m,n,o,p,q;f=Bc();g=0;h=f;while(g<9){i=b.S(g);if(X(i,e))W(h,i,Bz(e));g=g+1|0;}j=Bc();h=V();k=Dh(b);l=0;i=k;m=j;n=h;while(l<9){o=c.S(l);if(BP(i,o)){if(X(o,e))J(n,o);}else if(X(o,e))W(m,o,Bz(e));l=l+1|0;}p=N(BD,n.dV);Co(h,p);if(!a.gi)return Iq(a,p,e,
f,j,Ds(B5,[b,c]));h=new Ep;q=Ds(B5,[b,c]);BO(h,a,EF);h.fr=p;h.gW=d;h.e9=e;h.ht=j;h.hl=f;h.fl=q;return h;};
function H4(){let a=this;F.call(a);a.e5=0;a.gb=0;}
let Nr=(a,b,c)=>{a.e5=b;a.gb=c;},CZ=(a,b)=>{let c=new H4();Nr(c,a,b);return c;},I3=(a,b,c)=>{FD(a,b,R(Bk),c);FD(a,b,R(Br),c);FD(a,b,R(Bu),c);},FD=(a,b,c,d)=>{let e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w;e=(BJ(b,c)).data;f=e.length;g=0;while(g<f){a:{h=e[g];i=D3(h);j=a.e5;if(i<=(j*2|0)){if(!a.gb)break a;if(i<=j)break a;}k=Cr(j,9);while(true){if(!B7(k))break a;l=B9(k);j=0;while(true){m=l.data;n=m.length;if(j>=n)break;m[j]=m[j]+1|0;j=j+1|0;}o=N(Z,a.e5);p=o.data;j=0;while(true){q=a.e5;if(j>=q)break;p[j]=BA(h,m[j]);j
=j+1|0;}r=Dv(o,q);if(r!==null){b=new Z;q=0;while(q<n){CS(b,m[q],1);q=q+1|0;}p=N(BD,a.e5);m=p.data;q=0;c=Ca();s=Bc();i=0;t=c;u=s;while(i<9){v=h.S(i);if(Bd(r,i)){B8(t,v,b);w=new Z;j=1;while(j<=9){if(!Bd(b,j)&&X(v,j))Bw(w,j);j=j+1|0;}if(!BU(w))W(u,v,w);j=q+1|0;m[q]=v;q=j;}i=i+1|0;}b:{if(!a.gb){v=new G$;BO(v,a,s);v.gA=p;v.ex=l;v.hp=c;v.fQ=h;}else{q=1;while(q<=9){if(!Bd(b,q)){v=BA(h,q);if(K(v)>1){Cc(v,r);if(K(v)==1){b=h.S(Ba(v,0));v=new Hu;BO(v,a,EF);v.gL=p;v.fi=l;v.gZ=b;v.gN=q;v.hW=c;v.hU=s;v.hj=h;break b;}}}q=
q+1|0;}v=null;}}if(v!==null&&v.bR())d.bO(v);}}}g=g+1|0;}},FY=H(),GW=(a,b,c)=>{let d,e,f,g,h,i,j,k;d=(BJ(b,R(Bu))).data;e=d.length;f=0;c=c;while(f<e){g=d[f];h=0;while(h<9){i=g.S(h);j=i.dT;if(K(j)==1){k=Ba(j,0);j=new HQ;Hs(j,a,null,i,k);FX(c,j);}h=h+1|0;}f=f+1|0;}};
function Ie(){F.call(this);this.fc=0;}
let MR=(a,b)=>{a.fc=b;},DD=a=>{let b=new Ie();MR(b,a);return b;},K8=(a,b,c)=>{Fv(a,b,R(Bk),c);Fv(a,b,R(Br),c);Fv(a,b,R(Bu),c);},Fv=(a,b,c,d)=>{let e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v;e=(BJ(b,c)).data;f=e.length;g=0;while(g<f){a:{h=e[g];i=D3(h);j=a.fc;if(i>=(j*2|0)){k=Cr(j,9);while(true){if(!B7(k))break a;l=B9(k);m=N(BD,a.fc);n=m.data;i=0;o=n.length;while(i<o){n[i]=h.S(l.data[i]);i=i+1|0;}j=a.fc;p=N(Z,j);q=p.data;r=0;while(r<j){q[r]=n[r].dT;r=r+1|0;}s=Dv(p,j);if(s!==null){p=BE(a.fc);q=p.data;i=0;j=1;while(j<=
9){if(Bd(s,j)){r=i+1|0;q[i]=j;i=r;}j=j+1|0;}b=Ca();r=0;t=b;while(r<o){c=n[r];u=new Z;BH(u,s);B$(u,c.dT);B8(t,c,u);r=r+1|0;}c=Bc();r=0;v=c;while(r<9){u=h.S(r);if(!BI(CR(m),u)){t=new Z;i=1;while(i<=9){if(Bd(s,i)&&X(u,i))Bw(t,i);i=i+1|0;}if(!BU(t))W(v,u,t);}r=r+1|0;}u=new Ix;BO(u,a,c);u.f2=m;u.e2=p;u.hs=b;u.gq=h;if(Bn(u))d.bO(u);}}}}g=g+1|0;}};
function HV(){F.call(this);this.ft=0;}
let Lk=(a,b)=>{a.ft=b;},DU=a=>{let b=new HV();Lk(b,a);return b;},KA=(a,b,c)=>{IK(a,b,R(Br),R(Bu),c);IK(a,b,R(Bu),R(Br),c);},IK=(a,b,c,d,e)=>{let f,g,h,i,j,k,l,m,n,o,p,q,r,s,t;f=BE(10).data;g=1;while(g<=9){h=0;i=0;while(i<9){j=0;while(j<9){if(b.en.data[i].data[j].d3==g)h=h+1|0;j=j+1|0;}i=i+1|0;}f[g]=h;g=g+1|0;}k=BJ(b,c);l=Cr(a.ft,9);while(B7(l)){m=B9(l);n=new Z;o=0;while(true){p=m.data;if(o>=p.length)break;Bw(n,p[o]);o=o+1|0;}i=1;while(i<=9){g=f[i];o=a.ft;if((g+(o*2|0)|0)<=9){q=N(Z,o);r=q.data;o=0;while(true)
{g=a.ft;if(o>=g)break;r[o]=BA(k.data[p[o]],i);o=o+1|0;}s=Dv(q,g);if(s!==null){t=JK(a,b,c,d,n,s,i);if(Bn(t))e.bO(t);}}i=i+1|0;}}},JK=(a,b,c,d,e,f,g)=>{let h,i,j,k,l,m,n,o,p,q,r,s,t,u;h=BJ(b,d);i=BJ(b,c);j=V();k=V();l=0;c=j;d=k;while(l<9){if(Bd(e,l))J(c,i.data[l]);if(Bd(f,l))J(d,h.data[l]);l=l+1|0;}m=N(B5,c.dV+d.dV|0);i=m.data;l=0;while(l<c.dV){n=l*2|0;i[n]=Bl(c,l);i[n+1|0]=Bl(d,l);l=l+1|0;}o=V();p=Bc();l=0;c=o;d=p;while(l<9){q=0;while(q<9){if(Bd(f,l)&&Bd(e,q)){r=h.data[l].S(q);if(X(r,g)){J(c,r);W(d,r,Bz(g));}}q
=q+1|0;}l=l+1|0;}s=N(BD,c.dV);Co(o,s);t=Bc();n=0;d=t;while(n<9){a:{if(Bd(f,n)){i=h.data;u=BA(i[n],g);Cc(u,e);if(!BU(u)){q=0;while(true){if(q>=9)break a;if(Bd(u,q))W(d,i[n].S(q),Bz(g));q=q+1|0;}}}}n=n+1|0;}return Iq(a,s,g,p,t,m);};
function GC(){F.call(this);this.fe=0;}
let Jf=(a,b)=>{a.fe=b;},H2=a=>{let b=new GC();Jf(b,a);return b;},Mr=(a,b,c)=>{let d,e,f,g,h,i,j,k,l,m,n,o,p,q;d=!a.fe?2:3;e=0;while(e<9){f=0;while(f<9){a:{g=Bf(b,f,e);h=g.dT;if(K(h)==d){i=Bp(BL(g));while(true){if(!i.bb())break a;b:{j=i.bc();k=j.dT;if(K(k)==2){l=Bs(h);Cc(l,k);if(K(l)==1){l=Bp(BL(g));while(true){if(!l.bb())break b;m=l.bc();n=m.dT;if(K(n)==2){if(!a.fe){if(K(h)==2&&K(k)==2&&K(n)==2){o=Bs(h);BH(o,k);BH(o,n);p=Bs(h);B$(p,k);B$(p,n);q=K(o)==3&&!K(p)?1:0;}else q=0;if(q){o=HA(a,g,j,m,k,n);if(Bn(o))c.bO(o);}}
else{if(K(h)==3&&K(k)==2&&K(n)==2){o=Bs(h);BH(o,k);BH(o,n);p=Bs(h);B$(p,k);B$(p,n);q=K(o)==3&&K(p)==1?1:0;}else q=0;if(q){o=HA(a,g,j,m,k,n);if(Bn(o))c.bO(o);}}}}}}}}}}f=f+1|0;}e=e+1|0;}},HA=(a,b,c,d,e,f)=>{let g,h,i,j,k,l;g=Bs(e);B$(g,f);h=Ba(g,0);i=Bc();j=Da(BL(c));e=BL(d);f=j;BT(f,e);if(a.fe)BT(f,BL(b));e=j;Cw(e,b);Cw(e,c);Cw(e,d);e=Bp(e);j=i;while(e.bb()){k=e.bc();if(X(k,h))W(j,k,Bz(h));}e=new F0;l=a.fe;BO(e,a,i);e.fa=l;e.eG=b;e.eI=c;e.ew=d;e.fF=h;return e;};
function IG(){let a=this;F.call(a);a.f$=null;a.ge=null;}
let Mx=(a,b,c)=>{let d,e;d=!D2(b,a.f$)?M4(a,b):a.ge;e=new Ik;e.hn=a;Hz(d,e);Bx(b,a.f$);a.ge=d;d=O(d);while(P(d)){c.bO(Q(d));}},M4=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w;c=V();d=0;e=c;f=c;while(d<9){g=0;while(g<9){a:{h=Bf(b,g,d);i=h.dT;if(K(i)==2){j=Ba(i,0);k=Ba(i,j+1|0);l=V();m=V();Gd(a,b,h,j,k,l,2,new Z,null,m);i=O(m);while(true){if(!P(i))break a;n=Q(i);h=CJ();l=CJ();o=0;p=n;q=O(p);b:{c:while(true){if(!P(q)){o=EM(h,l);break b;}m=Q(q);r=O(BM(b));while(P(r)){s=BQ(b,Q(r),m.dY,m.dX);if(!o){if(BP(l,
s))break c;Bq(l,s);}else{if(BP(h,s)){o=0;break b;}Bq(h,s);}}o=o?0:1;}o=0;}if(o){q=Cf(2);m=O(p);l=q;while(P(m)){p=Q(m);if(K(p.dT)>2)J(l,p);}o=l.dV;if(o==1){h=Bl(l,0);l=Bc();m=new Z;Bw(m,j);Bw(m,k);W(l,h,m);r=new Gz;Dj(r,a,n,j,k,l);r.hV=h;if(!BI(e,r)&&Bn(r))J(f,r);}else{o=B1(o,2);if(o>0){t=new Z;l=O(q);while(P(l)){BH(t,(Q(l)).dT);}By(t,j);By(t,k);r=Gy(a,b,n,q,j,k);if(!BI(e,r)&&Bn(r))J(f,r);}else if(!o){d:{u=Bl(l,0);v=Bl(l,1);w=Bs(u.dT);BH(w,v.dT);By(w,j);By(w,k);if(K(w)!=1){if(K(w)<2)break d;l=O(LP(a,b,n,u,v,
j,k));while(true){if(!P(l))break d;r=Q(l);if(!BI(e,r)&&Bn(r))J(f,r);}}r=Gy(a,b,n,q,j,k);if(!BI(e,r)&&Bn(r))J(f,r);}r=JX(a,b,n,u,v,j,k);if(r!==null&&!BI(e,r)&&Bn(r))J(f,r);}}}}}}g=g+1|0;}d=d+1|0;}return c;},Gd=(a,b,c,d,e,f,g,h,i,j)=>{let k,l,m,n,o,p,q,r,s,t,u,v;k=f;J(k,c);l=Bs(h);m=O(BM(b));n=j;h=f;o=g+(-1)|0;while(P(m)){a:{p=Q(m);if(!Bg(p,i)){q=BQ(b,p,c.dY,c.dX);r=0;while(true){if(r>=9)break a;s=q.S(r);if(Bg(Bl(k,0),s)&&k.dV>=4)J(n,DY(f));else if(!BI(h,s)){t=s.dT;if(Bd(t,d)&&Bd(t,e)){BH(l,t);By(l,d);By(l,e);u
=B1(K(t),2);if(!(u&&K(l)!=1&&g<=0))Gd(a,b,s,d,e,f,u>0?o:g,l,p,j);}}r=r+1|0;}}}}e=k.dV-1|0;Eu(k,e);g=k.dV-1|0;k.dV=g;while(e<g){v=k.ed.data;d=e+1|0;v[e]=v[d];e=d;}k.ed.data[g]=null;k.d8=k.d8+1|0;},Gy=(a,b,c,d,e,f)=>{let g,h,i,j,k,l,m,n;g=d;h=Bs((Bl(g,0)).dT);By(h,e);By(h,f);i=Ba(h,0);j=Bc();k=null;h=O(d);while(P(h)){l=Q(h);if(k!==null){l=BL(l);BT(k,l);}else k=Da(BL(l));}h=Bp(k);b=d;d=j;while(h.bb()){m=h.bc();if(!BI(b,m)&&X(m,i))W(d,m,Bz(i));}n=N(BD,g.dV);Co(b,n);b=new If;Dj(b,a,c,e,f,j);b.hN=n;b.hY=i;return b;},LP
=(a,b,c,d,e,f,g)=>{let h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,bc,bd,be,bf,bg,bh,bi;h=V();i=Bs(d.dT);BH(i,e.dT);By(i,f);By(i,g);j=K(i);k=h;while(j<=7){l=O(BM(b));while(P(l)){a:{m=Q(l);n=DJ(b,m,d);if(Bg(n,DJ(b,m,e))){b:{o=D3(n);p=n.cg(d);q=n.cg(e);r=B1(j*2|0,o);if(r<=0){s=Cr(j,9);while(true){if(!B7(s))break b;t=B9(s);o=0;u=0;c:{while(true){v=t.data;w=v.length;if(u>=w)break;if(v[u]==p)o=1;else if(v[u]==q){o=0;break c;}u=u+1|0;}}if(o){x=N(Z,j);y=x.data;z=Bs(i);B$(z,d.dT);B$(z,e.dT);ba=N(BD,j-1|0);t=ba.data;u
=0;bb=0;while(bb<w){if(v[bb]==p){y[bb]=i;o=u;}else{bc=n.S(v[bb]);y[bb]=bc.dT;BH(z,y[bb]);o=u+1|0;t[u]=bc;}bb=bb+1|0;u=o;}if(K(z)==j){bd=Dv(x,j);if(bd!==null){x=BE(K(i));t=x.data;u=0;bb=1;while(bb<=9){if(Bd(i,bb)){o=u+1|0;t[u]=bb;u=o;}bb=bb+1|0;}y=BE(K(bd));t=y.data;u=0;bb=1;while(bb<=9){if(Bd(bd,bb)){o=u+1|0;t[u]=bb;u=o;}bb=bb+1|0;}bc=Bc();bb=0;z=bc;while(bb<9){be=n.S(bb);if(!BI(CR(ba),be)&&!Bg(d,be)&&!Bg(e,be)){m=new Z;o=1;while(o<=9){if(Bd(bd,o)&&X(be,o))Bw(m,o);o=o+1|0;}if(!BU(m))W(z,be,m);}bb=bb+1|0;}be
=Lj(a,c,f,g,bc,d,e,x,n,ba,y);if(Bn(be))J(k,be);}}}}}}if(r<0){ba=BE(7-K(i)|0).data;r=1;w=0;while(r<=9){if(r!=f&&r!=g&&!Bd(i,r)){o=w+1|0;ba[w]=r;w=o;}r=r+1|0;}p=j-2|0;o=ba.length;if(p<=o){bf=Cr(p,o);while(true){if(!B7(bf))break a;bg=B9(bf);x=BE(j).data;bb=0;while(true){t=bg.data;if(bb>=t.length)break;x[bb]=ba[t[bb]];bb=bb+1|0;}x[p]=f;x[j-1|0]=g;v=N(Z,j);t=v.data;bb=0;while(bb<j){t[bb]=BA(n,x[bb]);By(t[bb],q);bb=bb+1|0;}bh=K5(v,j);if(bh!==null){bi=new Z;bb=0;while(bb<x.length){Bw(bi,x[bb]);bb=bb+1|0;}be=ME(a,c,
f,g,i,bi,n,d,e,bh);if(Bn(be))J(k,be);}}}}}}}j=j+1|0;}return h;},ME=(a,b,c,d,e,f,g,h,i,j)=>{let k,l,m,n,o,p,q,r,s,t,u,v;k=BE(K(e));l=k.data;m=0;n=1;while(n<=9){if(Bd(e,n)){o=m+1|0;l[m]=n;m=o;}n=n+1|0;}p=g.cg(h);q=g.cg(i);By(j,p);By(j,q);r=Bc();o=0;e=r;while(o<9){if(Bd(j,o)){s=g.S(o);if(!Bg(s,h)&&!Bg(s,i)){t=new Z;n=1;while(n<=9){if(!Bd(f,n)&&X(s,n))Bw(t,n);n=n+1|0;}if(!BU(t))W(e,s,t);}}o=o+1|0;}l=BE(K(j));u=l.data;o=0;v=0;while(o<9){if(Bd(j,o)){m=v+1|0;u[v]=o;v=m;}o=o+1|0;}e=new FV;Dj(e,a,b,c,d,r);e.h4=h;e.h5
=i;e.ho=k;e.gg=f;e.gf=g;e.fu=l;return e;},JX=(a,b,c,d,e,f,g)=>{let h,i,j,k,l,m,n,o,p;h=null;i=null;j=O(BM(b));while(P(j)){k=Q(j);l=BQ(b,k,d.dY,d.dX);if(Bg(l,BQ(b,k,e.dY,e.dX))){m=0;n=0;o=0;while(o<9){p=l.S(o);if(!Bg(p,d)&&!Bg(p,e)){if(X(p,f))m=1;if(X(p,g))n=1;}o=o+1|0;}if(!m)h=l;if(!n)i=l;}}l=null;j=Bc();if(h!==null){b=Bz(g);k=j;W(k,d,b);W(k,e,Bz(g));}else if(i===null){h=l;f=(-1);g=(-1);}else{k=Bz(f);b=j;W(b,d,k);W(b,e,Bz(f));m=f;h=i;f=g;g=m;}if(h===null)return null;b=new IA;Dj(b,a,c,f,g,j);b.hB=d;b.hC=e;b.hM
=f;b.hu=g;b.hJ=h;return b;};
function Hq(){F.call(this);this.eX=null;}
let LA=(a,b,c)=>{let d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y;Bx(b,a.eX);d=V();e=Bc();f=new Z;g=null;h=O(BM(b));i=d;j=d;k=e;a:while(true){if(!P(h)){l=0;b:while(true){if(l>=9){m=O(BM(a.eX));c:while(true){if(!P(m)){if(j.dV==1){b=Bl(j,0);n=Bc();k=Bs(b.dT);Cc(k,f);W(n,b,k);k=new HD;BO(k,a,n);k.gs=b;k.hD=f;c.bO(k);}else if(K(f)==1){o=Ba(f,0);if(g!==null){k=g;if(!CT(k)){n=Bc();k=Bp(k);p=n;while(k.bb()){m=k.bc();if(X(m,o))W(p,m,Bz(o));}if(!D6(p)){q=N(BD,j.dV);Co(i,q);k=new Hr;BO(k,a,n);k.g$=q;k.gH=o;c.bO(k);}}}if
(j.dV==2)Gr(a,c,d,e,f,g,b);}else if(g!==null&&!CT(g)){if(j.dV==2)Gr(a,c,d,e,f,g,b);KE(a,c,d,e,f,g,b);}return;}n=Q(m);q=BJ(a.eX,n);o=0;while(true){r=q.data;if(o>=r.length)break;k=r[o];s=1;while(s<=9){t=K(BA(k,s));if(t&&t!=2)break c;s=s+1|0;}o=o+1|0;}}return;}u=0;while(u<9){m=Bf(a.eX,u,l);if(!m.d3&&K(m.dT)!=2)break b;u=u+1|0;}l=l+1|0;}return;}q=BJ(b,Q(h));v=0;while(true){r=q.data;if(v>=r.length)break;p=r[v];s=1;while(s<=9){w=BA(p,s);t=K(w);if(t&&t!=2){x=V();y=Ba(w,0);n=x;while(y>=0){m=p.S(y);if(K(m.dT)>=3)J(n,
m);y=Ba(w,y+1|0);}if(n.dV==1){m=Bl(n,0);if(!BI(i,m))J(j,m);if(!CW(k,m))W(k,m,new Z);Bw(Ch(k,m),s);Bw(f,s);Dn(Bf(a.eX,m.dY,m.dX),s);if(g!==null){n=BL(m);BT(g,n);}else g=Da(BL(m));He(g,d);if(j.dV>1&&K(f)>1&&CT(g))return;}if(Bj(x))break a;}s=s+1|0;}v=v+1|0;}}},KE=(a,b,c,d,e,f,g)=>{let h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,bc,bd,be,bf,bg,bh,bi,bj,bk;h=O(BM(g));i=c;j=f;k=c;l=c;while(P(h)){m=Q(h);n=null;o=O(i);a:{while(P(o)){p=Q(o);q=BQ(g,m,p.dY,p.dX);if(n!==null){if(!Bg(n,q)){n=null;break a;}q=n;}n=q;}}b:{if
(n!==null){r=V();q=Bp(j);f=r;while(q.bb()){p=q.bc();if(Bg(DJ(g,m,p),n))J(f,p);}s=2;p=r;while(true){if(s>6)break b;c:{t=f.dV;if(t>=s){u=new DQ;v=s-1|0;Eq(u,v,t);while(true){if(!B7(u))break c;w=N(Z,s);x=w.data;y=N(BD,v);z=y.data;ba=new Z;bb=B9(u);t=0;while(true){bc=bb.data;if(t>=bc.length)break;o=Bl(f,bc[t]);z[t]=o;bd=o.dT;x[t]=bd;BH(ba,bd);t=t+1|0;}x[v]=e;if(K(ba)==s){be=Dv(w,s);if(be!==null){bf=new CM;m=new C6;t=f.dV;DB(m,t<6?11:t*2|0);Dg(bf,m);o=O(p);while(P(o)){Bq(bf,Q(o));}bg=z.length;t=0;q=bf;while(t<bg)
{Cw(q,z[t]);t=t+1|0;}He(bf,c);if(!CT(q)){bh=Bc();o=Bp(q);q=bh;while(o.bb()){bi=o.bc();bj=Bs(bi.dT);B$(bj,be);if(!BU(bj))W(q,bi,bj);}if(!D6(q)){z=N(BD,k.dV);Co(l,z);bk=new IN;BO(bk,a,bh);bk.g7=z;bk.hr=d;bk.hA=e;bk.h6=y;bk.fZ=be;bk.hk=n;b.bO(bk);}}}}}}}s=s+1|0;}}}}},Gr=(a,b,c,d,e,f,g)=>{let h,i,j,k,l,m,n,o,p,q,r,s,t,u;h=c;i=Bl(h,0);h=Bl(h,1);j=new Z;BH(j,i.dT);B$(j,h.dT);Cc(j,e);if(K(j)!=1)return;k=O(BM(g));f=c;l=d;while(P(k)){m=Q(k);n=null;o=O(f);a:{while(P(o)){p=Q(o);q=BQ(g,m,p.dY,p.dX);if(n!==null){if(!Bg(n,
q)){n=null;break a;}q=n;}n=q;}}if(n!==null){r=Ba(j,0);s=Bc();t=Bs(i.dT);Cc(t,Ch(l,i));By(t,r);u=s;W(u,i,t);o=Bs(h.dT);Cc(o,Ch(l,h));By(o,r);W(u,h,o);u=new IE;BO(u,a,s);u.gV=i;u.gT=h;u.hG=d;u.hm=e;u.g4=r;u.hz=n;b.bO(u);}}};
function D1(){F.call(this);this.ee=0;}
let HP=(a,b)=>{a.ee=b;},KM=a=>{let b=new D1();HP(b,a);return b;},J8=(a,b,c)=>{let d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,bc,bd,be,bf,bg,bh,bi,bj,bk,bl,bm,bn,bo,bp,bq,br,bs,bt,bu,bv;d=V();e=Ca();f=0;g=d;h=e;while(f<9){i=0;while(i<9){j=Bf(b,i,f);if(K(Ct(j))>=2){k=0;l=V();m=Bp(BL(j));n=l;while(m.bb()){o=m.bc();p=K(Ct(o));if(p==1)k=1;else if(p>=2&&p<=a.ee)J(n,o);}if(!k&&!Bj(l)){J(g,j);B8(h,j,l);}}i=i+1|0;}f=f+1|0;}if(Im(e)<a.ee)return;q=Cr(2,E_(g));while(B7(q)){a:{r=(B9(q)).data;s=Bl(g,r[0]);t=K(Ct(s));u
=Bl(g,r[1]);v=K(Ct(u));w=Da(CN(h,s));m=CN(h,u);b=w;BW(b,m);BT(b,d);b=w;Cw(b,s);Cw(b,u);if(CK(b)>=(a.ee-2|0)){x=DY(w);y=new DQ;p=a.ee-2|0;o=x;Eq(y,p,E_(o));while(true){if(!B7(y))break a;p=a.ee;r=N(BD,p);z=r.data;ba=BE(p).data;z[0]=s;ba[0]=t;z[1]=u;ba[1]=v;bb=B9(y);bc=0;while(true){bd=bb.data;if(bc>=bd.length)break;p=bc+2|0;z[p]=Bl(o,bd[bc]);ba[p]=K(Ct(z[p]));bc=bc+1|0;}be=B0();bc=0;bf=be;while(bc<a.ee){m=CN(h,z[bc]);if(bc)BT(bf,m);else BW(bf,m);bc=bc+1|0;}b=be;if(CK(b)>=2){bg=Bc();bd=BE(a.ee).data;bh=V();bi=
Ca();j=bh;bj=bi;while(true){bk=0;while(true){if(bd[bk]){bc=0;bd[bk]=bd[bk]-1|0;}else{bc=1;bd[bk]=ba[bk]-1|0;bk=bk+1|0;}p=a.ee;if(bk>=p)break;if(!bc)break;}bl=BE(p);bm=bl.data;bc=0;while(true){p=a.ee;if(bc>=p)break;bn=Ct(z[bc]);bo=Ba(bn,0);bp=0;while(bp<bd[bc]){bo=Ba(bn,bo+1|0);bp=bp+1|0;}bm[bc]=bo;bc=bc+1|0;}bq=1;bf=null;n=Cr(2,p);b:{while(B7(n)){br=(B9(n)).data;if(bm[br[0]]==bm[br[1]]){bs=z[br[0]];bt=z[br[1]];if(BP(BL(bs),bt)){bq=0;break b;}}}}c:{if(!bq)bu=bf;else{m=Bp(b);while(m.bb()){bu=m.bc();bn=Bs(Ct(bu));bc
=0;while(bc<a.ee){By(bn,bm[bc]);bc=bc+1|0;}if(BU(bn)){bq=0;break c;}}bu=bf;}}if(!bq)B8(bj,bl,bu);else J(j,bl);p=1;bc=0;while(bc<a.ee){if(bd[bc])p=0;bc=bc+1|0;}if(!p)continue;else break;}bc=0;m=bh;n=bg;while(bc<a.ee){j=z[bc];bn=Ct(j);bo=Ba(bn,0);while(bo>=0){bv=0;bf=O(m);while(P(bf)){if((Q(bf)).data[bc]==bo)bv=1;}if(!bv){if(!CW(n,j))W(n,j,Bz(bo));else Bw(Ch(n,j),bo);}bo=Ba(bn,bo+1|0);}bc=bc+1|0;}bj=Iv(a,bg,r,bi);if(Bn(bj))c.bO(bj);}}}}}},Hp=H(D1),Nz=(a,b,c)=>{let d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,
ba,bb,bc,bd,be,bf,bg,bh,bi,bj;d=V();e=Ca();f=0;d=d;g=e;while(f<9){h=0;while(h<9){i=Bf(b,h,f);if(K(i.dT)>=2){j=0;k=V();l=Bp(BL(i));m=k;while(l.bb()){n=l.bc();o=K(n.dT);if(o==1)j=1;else if(o==2)J(m,n);}if(!j&&!Bj(k)){J(d,i);B8(g,i,k);}}h=h+1|0;}f=f+1|0;}p=e.d1;if(p<2)return;q=Cr(2,p);while(B7(q)){r=(B9(q)).data;s=N(BD,2);t=s.data;u=BE(2).data;t[0]=Bl(d,r[0]);u[0]=K(t[0].dT);t[1]=Bl(d,r[1]);u[1]=K(t[1].dT);v=B0();b=CN(g,t[0]);n=v;BW(n,b);BT(n,CN(g,t[1]));w=v;if(CK(w)>=2){x=Bc();y=V();z=Ca();ba=t[0].dT;l=t[1].dT;bb
=Ba(ba,0);b=y;v=z;while(bb>=0){bc=Ba(l,0);while(bc>=0){r=BE(2);u=r.data;u[0]=bb;u[1]=bc;bd=1;be=null;if(bb==bc){n=BL(t[0]);m=t[1];if(BP(n,m))bd=0;}a:{if(!bd)bf=be;else{m=Bp(w);while(m.bb()){bf=m.bc();bg=Bs(bf.dT);bh=0;while(bh<2){By(bg,u[bh]);bh=bh+1|0;}if(BU(bg)){bd=0;break a;}}bf=be;}}if(!bd)B8(v,r,bf);else J(b,r);bc=Ba(l,bc+1|0);}bb=Ba(ba,bb+1|0);}bh=0;ba=y;l=x;while(bh<2){m=t[bh];w=m.dT;p=Ba(w,0);while(p>=0){bi=0;n=O(ba);while(P(n)){if((Q(n)).data[bh]==p)bi=1;}if(!bi){if(!CW(l,m))W(l,m,Bz(p));else Bw(Ch(l,
m),p);}p=Ba(w,p+1|0);}bh=bh+1|0;}bj=Iv(a,x,s,z);if(Bn(bj))c.bO(bj);}}};
function GK(){let a=this;F.call(a);a.eU=0;a.ez=0;a.eo=0;a.eV=0;a.em=null;a.ej=null;a.gk=null;a.f4=null;}
let Nv=(a,b,c,d,e)=>{a.em=Cg();a.gk=null;a.f4=null;a.eU=b;a.ez=c;a.eo=d;a.eV=e;},BR=(a,b,c,d)=>{let e=new GK();Nv(e,a,b,c,d);return e;},Ey=a=>{let b,c;b=a.eV;if(b>=2)return 9.5+0.5*(b-2|0);if(b>0)return 8.5+0.5*b;if(a.eo)return 7.5;if(a.ez)return 8.5;if(a.eU)return 8.0;c=new CQ;Y(c);S(c);},EB=(a,b,c,d)=>{let e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb;e=V();f=0;g=e;while(f<9){h=0;while(h<9){a:{i=Bf(b,h,f);j=K(i.dT);if(!i.d3&&j>1){k=1;while(true){if(k>9)break a;if(X(i,k)){l=Bt(i,k,1);if(!(K(l.dU.dT)>2&&
!d)){m=V();n=V();o=BG();p=BG();BK(o,l);q=CX(o);r=CX(p);j=0;s=q;t=r;u=q;v=r;r=r;w=m;q=q;while(!(Bj(s)&&Bj(t))){j=j+1|0;while(!Bj(s)){x=CO(u,0);y=Bp(EK(a,b,x,c));while(y.bb()){z=y.bc();if(!Hv(a,x,z)){CB(v,z);BK(p,z);}}}j=j+1|0;ba=B1(j,4);while(!Bj(t)){x=Bp(FB(a,b,CO(r,0),a.em,p,c,d));while(x.bb()){y=x.bc();if(ba>=0&&Dr(y,l))J(w,y);if(!Cl(o,y)){CB(q,y);BK(o,y);}}}}if(d){q=BG();r=BG();BK(q,l);F3(a,b,q,r,c,n,l);q=Bt(l.dU,l.dW,0);l=BG();r=BG();BK(r,q);F3(a,b,l,r,c,n,q);}y=O(m);while(P(y)){x=Q(y);l=new Fy;r=null;q
=l;w=x;while(w!==null){o=new Cj;p=w.dU;bb=w.dW;ba=w.dZ?0:1;t=w.eP;o.d4=Cf(1);o.dU=p;o.dW=bb;o.dZ=ba;o.eP=t;o.fo=r;o.eZ=null;r=w.fo;Ig(q,0,o);w=Bj(w.d4)?null:Bl(w.d4,0);}o=null;r=q;q=Fq(r,r.fg,null,0);while(Id(q)){w=E7(q);if(o!==null)J(o.d4,w);o=w;}l=Kw(a,b,x,E7(FG(r,0)),c,d);if(Bn(l))J(g,l);}r=O(n);while(P(r)){l=J9(a,b,Q(r),c,d);if(Bn(l))J(g,l);}}}k=k+1|0;}}}h=h+1|0;}f=f+1|0;}return e;},KS=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,bc,bd;c=V();d=0;e=c;while(d<9){f=0;while(f<9){a:{g=Bf(b,
f,d);h=K(g.dT);if(!g.d3){i=B1(h,2);if(i<=0){if(h<=1)break a;if(!a.ez)break a;}j=Bc();k=Bc();l=null;m=null;n=1;o=B1(h,3);p=j;q=k;while(n<=9){if(X(g,n)){r=Bt(g,n,1);s=Bt(g,n,0);t=BG();u=BG();v=o>=0&&!a.eo&&a.ez?1:0;w=!a.ez&&!a.eo?0:1;x=BG();y=BG();BK(t,r);z=EL(a,b,t,u);if(w&&z!==null){z=z.data;ba=Gt(a,z[0],z[1],r,r,1);if(Bn(ba))J(e,ba);}BK(y,s);z=EL(a,b,x,y);if(w&&z!==null){z=z.data;ba=Hm(a,z[0],z[1],s,s,1);if(Bn(ba))J(e,ba);}b:{if(v){ba=CA(t);bb=ba;ba=ba;while(BY(bb)){bc=Cp(ba);bd=Cn(x,bc);if(bd!==null){bc=Hm(a,
bc,bd,r,bc,0);if(Bn(bc))J(e,bc);}}ba=CA(u);bd=ba;r=ba;while(true){if(!BY(bd))break b;ba=Cp(r);bc=Cn(y,ba);if(bc!==null){ba=Gt(a,ba,bc,s,bc,0);if(Bn(ba))J(e,ba);}}}}if(!a.eo)Nt(a,b,c,g,n,t,u);W(p,B2(n),t);W(q,B2(n),u);if(l!==null){BT(l,t);BT(m,u);}else{l=BG();m=BG();BW(l,t);BW(m,u);}}n=n+1|0;}if(!a.eo){if(i){if(!a.eU)break a;if(i<=0)break a;}ba=CA(l);s=ba;r=ba;while(BY(s)){bc=G5(a,g,Cp(r),j);if(Bn(bc))J(e,bc);}ba=CA(m);s=ba;r=ba;while(true){if(!BY(s))break a;bc=G5(a,g,Cp(r),k);if(Bn(bc))J(e,bc);}}}}f=f+1|0;}d
=d+1|0;}return c;},Nt=(a,b,c,d,e,f,g)=>{let h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y;h=O(BM(b));i=c;while(P(h)){a:{j=BQ(b,Q(h),d.dY,d.dX);k=BA(j,e);l=B1(K(k),2);if(l){if(!a.eU)break a;if(l<=0)break a;}if(Bg(j.S(Ba(k,0)),d)){m=Bc();n=Bc();o=BG();p=BG();q=Ba(k,0);r=m;s=n;t=o;u=p;while(q>=0){v=j.S(q);if(Bg(v,d)){W(r,B2(q),f);W(s,B2(q),g);BW(t,f);BW(u,g);}else{w=Bt(v,e,1);x=BG();y=BG();BK(x,w);EL(a,b,x,y);W(r,B2(q),x);W(s,B2(q),y);BT(t,x);BT(u,y);}q=Ba(k,q+1|0);}c=CA(o);v=c;c=c;while(BY(v)){t=II(a,j,e,Cp(c),m);if(Bn(t))J(i,
t);}c=CA(p);m=c;c=c;while(true){if(!BY(m))break a;t=II(a,j,e,Cp(c),n);if(Bn(t))J(i,t);}}}}},EK=(a,b,c,d)=>{let e,f,g,h,i,j,k,l,m;a:{e=B0();if(d){f=c.dU.dT;g=1;h=e;while(true){if(g>9)break a;if(g!=c.dW&&Bd(f,g))Bq(h,DT(c.dU,g,0,c,C0,E(63)));g=g+1|0;}}}i=O(BM(b));f=e;while(P(i)){j=Q(i);k=c.dU;k=BQ(b,j,k.dY,k.dX);l=0;while(l<9){m=k.S(l);if(!Bg(m,c.dU)&&X(m,c.dW))Bq(f,DT(m,c.dW,0,c,Ev(k),null));l=l+1|0;}}return e;},Ev=b=>{if(b instanceof Bk)return D7;if(!(b instanceof Br))return D5;return DC;},FB=(a,b,c,d,e,f,g)=>
{let h,i,j,k,l,m,n,o,p,q;a:{h=B0();if(f){i=c.dU.dT;if(K(i)==2){j=Ba(i,0);if(j==c.dW)j=Ba(i,j+1|0);k=DT(c.dU,j,1,c,C0,E(64));l=k.dU;m=l.dY;f=l.dX;l=Bf(b,m,f);n=Bf(d,m,f);m=1;while(true){if(m>9){Bq(h,k);break a;}if(X(n,m)&&!X(l,m)){o=Cn(e,Bt(l,m,0));if(o===null)break;J(k.d4,o);}m=m+1|0;}S(FP(E(65)));}}}b:{if(g){p=Cf(3);n=p;J(n,R(Bk));J(n,R(Bu));J(n,R(Br));i=O(p);p=h;while(true){if(!P(i))break b;l=Q(i);n=c.dU;n=BQ(b,l,n.dY,n.dX);o=BA(n,c.dW);if(K(o)==2){m=Ba(o,0);q=n.S(m);if(Bg(q,c.dU))q=n.S(Ba(o,m+1|0));k=DT(q,
c.dW,1,c,Ev(n),null);l=CY(n);o=k.dU;l=BQ(d,l,o.dY,o.dX);o=BA(n,k.dW);q=BA(l,k.dW);Cc(q,o);g=Ba(q,0);while(g>=0){l=Cn(e,Bt(n.S(g),k.dW,0));if(l===null)S(FP(E(65)));J(k.d4,l);g=Ba(q,g+1|0);}Bq(p,k);}}}}return h;},Hv=(a,b,c)=>{while(!Bj(b.d4)){b=Bl(b.d4,0);if(Dr(b,c))return 1;}return 0;},F3=(a,b,c,d,e,f,g)=>{let h,i,j,k,l,m,n,o,p,q,r,s;h=CX(c);i=CX(d);j=h;k=i;l=h;m=f;n=f;o=i;p=i;h=h;a:while(!(Bj(j)&&Bj(k))){while(!Bj(j)){q=CO(l,0);f=Bp(EK(a,b,q,e));while(f.bb()){r=f.bc();if(Dr(g,Bt(r.dU,r.dW,1))&&!BI(m,r))J(n,
r);if(!Hv(a,q,r)&&!Cl(d,r)){CB(o,r);BK(d,r);}}}while(true){if(Bj(k))continue a;f=Bp(FB(a,b,CO(p,0),a.em,d,e,1));while(f.bb()){s=f.bc();if(Dr(g,Bt(s.dU,s.dW,0))&&!BI(m,s))J(n,s);if(!Cl(c,s)){CB(h,s);BK(c,s);}}}}},EL=(a,b,c,d)=>{let e,f,g,h,i,j,k,l,m,n,o,$$je;Bx(b,a.em);a:{b:{try{e=CX(c);f=CX(d);}catch($$e){$$je=Bb($$e);c=$$je;break b;}g=e;h=f;i=f;j=e;f=f;e=e;c:{d:{while(true){try{if(Bj(g)&&Bj(h))break;e:{if(!Bj(g)){k=Bp(EK(a,b,CO(j,0),a.eo?0:1));while(k.bb()){l=k.bc();m=Bt(l.dU,l.dW,1);if(Cl(c,m))break c;if(!Cl(d,
l)){BK(d,l);CB(i,l);}}}else{k=CO(f,0);n=FB(a,b,k,a.em,d,a.eo?0:1,1);if(a.ez)JM(k);k=Bp(n);while(true){if(!k.bb())break e;m=k.bc();l=Bt(m.dU,m.dW,0);if(Cl(d,l))break d;if(!Cl(c,m)){BK(c,m);CB(e,m);}}}}if(!Bj(g))continue;if(!Bj(h))continue;if(a.eV<=0)continue;k=O(My(a,b,a.em,d));}catch($$e){$$je=Bb($$e);c=$$je;break b;}k=k;while(true){try{if(!P(k))break;l=Q(k);if(!Cl(d,l)){BK(d,l);CB(i,l);}continue;}catch($$e){$$je=Bb($$e);c=$$je;break b;}}try{continue;}catch($$e){$$je=Bb($$e);c=$$je;break b;}}try{c=null;}catch
($$e){$$je=Bb($$e);c=$$je;break b;}Bx(a.em,b);return c;}try{c=Cn(d,l);o=Ds(Cj,[m,c]);}catch($$e){$$je=Bb($$e);c=$$je;break b;}Bx(a.em,b);return o;}try{c=Cn(c,m);o=Ds(Cj,[c,l]);break a;}catch($$e){$$je=Bb($$e);c=$$je;}}Bx(a.em,b);S(c);}Bx(a.em,b);return o;},My=(a,b,c,d)=>{let e,f,g,h,i,j,k,l,m,n,o,p,q,$$je;e=V();if(a.ej===null){f=V();a.ej=f;g=FZ(0);J(f,g);f=a.ej;g=CZ(2,0);J(f,g);f=a.ej;g=DD(2);J(f,g);f=a.ej;g=DU(2);J(f,g);h=a.eV;i=B1(h,4);if(i>=0){if(i>=0){f=a.ej;g=BR(1,1,0,0);J(f,g);}h=a.eV;if(h>=5){f=a.ej;g
=BR(1,1,0,h-3|0);J(f,g);}}else{if(h>=2){f=a.ej;g=BR(0,0,0,0);J(f,g);}if(a.eV>=3){f=a.ej;g=BR(1,0,0,0);J(f,g);}}}i=0;j=e;k=null;while(i<a.ej.dV&&Bj(j)){f=Bl(a.ej,i);a:{try{f.bd(b,M0(a,c,b,d,e));break a;}catch($$e){$$je=Bb($$e);if($$je instanceof BF){g=$$je;}else{throw $$e;}}l=g;if(Eh===null){f=new Gx;f.h9=null;f.hL=U();f.h$=Df(32);f.hQ=0;f.h3=k;Eh=f;}g=Eh;m=CY(l);if(m.fU===null)m.fU=Cs(m.eR.$meta.name);f=m.fU;n=g;CD(n,f);o=l.gn;if(o!==null){f=U();I(I(f,E(66)),o);CD(n,T(f));}b:{o=g;CD(o,E(67));p=l.h7;if(p!==null)
{p=p.data;h=p.length;q=0;while(true){if(q>=h)break b;f=p[q];CD(n,E(68));m=E(2);if(f!==null)m=f.g();CD(o,m);CD(o,E(67));q=q+1|0;}}}f=l.gj;if(f!==null&&f!==l){CD(n,E(69));l.gj.cQ(g);}}i=i+1|0;}return e;},Kw=(a,b,c,d,e,f)=>{let g,h,i,j,k,l,m,n;g=B0();h=c;while(!Bj(h.d4)){Bq(g,h.dU);h=Bl(h.d4,0);}i=B0();j=B0();k=i;h=j;l=c;while(!Bj(l.d4)){m=l.dU;m=Bp(BL(Bf(b,m.dY,m.dX)));while(m.bb()){n=m.bc();if(!BP(g,n)&&X(n,l.dW)){if(!l.dZ)Bq(h,Bt(n,l.dW,0));else Bq(k,Bt(n,l.dW,0));}}l=Bl(l.d4,0);}BT(i,j);g=Bc();j=Bp(k);i=g;while
(j.bb()){k=j.bc();l=Ch(i,k.dU);if(l!==null)Bw(l,k.dW);else W(i,k.dU,Bz(k.dW));}b=new HL;Dc(b,a,g,e,f);b.fD=(-1);b.go=c;b.f6=d;return b;},J9=(a,b,c,d,e)=>{let f,g,h,i;f=Bc();if(!c.dZ){b=c.dU;g=Bz(c.dW);W(f,b,g);}else{h=new Z;i=1;while(i<=9){if(i!=c.dW&&X(c.dU,i))Bw(h,i);i=i+1|0;}b=c.dU;W(f,b,h);}b=new Hw;Dc(b,a,f,d,e);b.fB=(-1);b.et=c;return b;},Hm=(a,b,c,d,e,f)=>{let g,h;g=Bc();h=Bs(e.dU.dT);CS(h,e.dW,0);if(!BU(h)){e=e.dU;W(g,e,h);}return Gw(a,g,d,b,c,f,a.eo);},Gt=(a,b,c,d,e,f)=>{let g,h;g=Bc();h=e.dU;e=Bz(e.dW);W(g,
h,e);return Gw(a,g,d,b,c,f,a.eo);},G5=(a,b,c,d)=>{let e,f,g,h,i;e=Bc();if(!c.dZ){f=c.dU;g=Bz(c.dW);W(e,f,g);}else{g=Bs(c.dU.dT);CS(g,c.dW,0);if(!BU(g)){f=c.dU;W(e,f,g);}}f=Ca();h=1;g=d;while(h<=9){if(X(b,h)){i=Cn(Ch(g,B2(h)),c);B8(f,B2(h),i);}h=h+1|0;}c=new Fx;Dc(c,a,e,1,1);c.g_=b;c.fj=f;return c;},II=(a,b,c,d,e)=>{let f,g,h,i,j,k;f=Bc();if(!d.dZ){g=d.dU;h=Bz(d.dW);W(f,g,h);}else{h=Bs(d.dU.dT);CS(h,d.dW,0);if(!BU(h)){g=d.dU;W(f,g,h);}}g=Ca();i=BA(b,c);j=0;h=e;while(j<9){if(Bd(i,j)){k=Cn(Ch(h,B2(j)),d);B8(g,
B2(j),k);}j=j+1|0;}d=new Ef;Dc(d,a,f,1,1);d.fS=b;d.gB=c;d.ff=g;return d;},GO=(a,b)=>{if(!a.ez&&!a.eU){if(!b.eC)return E(70);return E(71);}return null;},Lf=(a,b,c)=>{let d,e,f,g;d=a.gk;if(d!==null&&D2(b,d)){b=Bp(a.f4);while(b.bb()){c.bO(b.bc());}return;}if(!a.eU&&!a.ez){e=EB(a,b,0,1);f=EB(a,b,1,0);d=EB(a,b,1,1);g=e;BW(g,f);BW(g,d);}else e=KS(a,b);d=new F4;d.hx=a;Hz(e,d);d=Cg();a.gk=d;Bx(b,d);b=Da(e);a.f4=b;b=Bp(b);while(b.bb()){c.bO(b.bc());}},Dl=H(0),G2=H(),NC=(a,b,c)=>{let d,e,f,g,h,i,j,k,l,m,n,o,p;d=O(BM(b));while
(P(d)){e=BJ(b,Q(d));f=0;while(f<9){g=e.data[f];h=new Z;i=0;while(i<9){j=g.S(i);k=j.d3;if(k){if(!Bd(h,k))Bw(h,k);else{l=new GB;m=g.g();n=U();I(I(Bh(I(n,E(72)),k),E(73)),m);o=T(n);p=Ds(F,[DZ(k),g.g()]);l.hK=j;l.hw=g;l.h2=a;D4(l,a,o,E(74),p);c.bO(l);}}i=i+1|0;}f=f+1|0;}}},Ht=H(),IV=(a,b,c)=>{let d,e,f,g,h,i;d=0;e=0;while(e<9){f=0;while(f<9){if(!(Bf(b,f,e)).d3)d=d+1|0;f=f+1|0;}e=e+1|0;}if(!d)c.bO(Ea(a,E(75),E(76),N(F,0)));else if(d>64){g=81-d|0;h=new C1;i=N(F,1);i.data[0]=B2(g);D4(h,a,E(77),E(78),i);c.bO(h);}},Ga
=H(),Js=(a,b,c)=>{let d,e,f,g,h,i,j,k,l;d=new Z;e=0;while(e<9){f=0;while(f<9){g=(Bf(b,f,e)).d3;if(g)Bw(d,g);f=f+1|0;}e=e+1|0;}if(K(d)<8){h=E(3);i=1;while(i<=9){if(!Bd(d,i)){if(h===E(3))g=1;else if(!(E(3) instanceof BX))g=0;else{b=E(3);g=h.d9!==b.d9?0:1;}if(!g){j=U();I(I(j,h),E(79));h=T(j);}b=U();Bh(I(b,h),i);h=T(b);}i=i+1|0;}k=new C1;l=N(F,1);l.data[0]=h;D4(k,a,E(80),E(81),l);c.bO(k);}};
function Ih(){let a=this;F.call(a);a.el=null;a.e$=null;a.gv=0;}
let ML=(a,b,c)=>{let d,e,f;Bx(b,a.el);if(Em(a,a.el,0)){Bx(b,a.e$);Em(a,a.e$,1);if(!D2(a.el,a.e$)){d=new GA;e=a.el;f=a.e$;ED(d,a);d.gE=0;d.fx=b;d.gG=e;d.gF=f;c.bO(d);}else if(a.gv){e=new GN;d=a.el;ED(e,a);e.g6=b;e.g3=d;c.bO(e);}return;}Bx(b,a.el);GS(HN(a.el));c.bO(D2(b,a.el)?Ea(a,E(82),E(83),N(F,0)):Em(a,a.el,0)?Ea(a,E(82),E(84),N(F,0)):Ea(a,E(82),E(83),N(F,0)));},Em=(a,b,c)=>{return Gk(a,b,c,null,new FW,new FY);},Gk=(a,b,c,d,e,f)=>{let g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,$$je;g=O(BM(b));a:{while(P(g)){h=BJ(b,Q(g));i
=0;while(i<9){j=h.data[i];k=1;while(k<=9){if(!L7(j,k)&&BU(BA(j,k))){i=0;break a;}k=k+1|0;}i=i+1|0;}}i=1;}if(!i)return 0;g=null;j=f;l=e;while(true){if(g!==null)g.bg();m=Ii();b:{try{GW(j,b,m);HI(l,b,m);break b;}catch($$e){$$je=Bb($$e);if($$je instanceof BF){}else{throw $$e;}}}g=m.fp;if(g===null)break;}k=0;c:{while(k<9){n=0;while(n<9){if(!GJ(b,n,k)){i=0;break c;}n=n+1|0;}k=k+1|0;}i=1;}if(i)return 1;j=null;o=10;p=0;while(p<9){q=0;while(q<9){r=Bf(b,q,p);if(!r.d3){s=K(r.dT);if(s<o){o=s;j=r;}}q=q+1|0;}p=p+1|0;}l=Cg();i
=!c?0:8;k=!c?9:(-1);n=!c?1:(-1);t=0;if(d!==null)t=d.c1(9);while(i!=k){u=i+1|0;if(d!==null)u=((i+t|0)%9|0)+1|0;if(X(j,u)){Bx(b,l);E8(j,u);if(Gk(a,b,c,d,e,f))return 1;Bx(l,b);}i=i+n|0;}return 0;};
function Z(){F.call(this);this.d0=0;}
let HE=b=>{let c,d;if(b>=0&&b<=31)return;c=new BN;d=U();Bh(I(d,E(85)),b);Ci(c,T(d));S(c);},Bw=(a,b)=>{HE(b);a.d0=a.d0|1<<b;},CS=(a,b,c)=>{if(!c)By(a,b);else Bw(a,b);},By=(a,b)=>{HE(b);a.d0=a.d0&(1<<b^(-1));},Hb=a=>{a.d0=0;},Bd=(a,b)=>{let c,d;if(b<0){c=new BN;d=U();Bh(I(d,E(85)),b);Ci(c,T(d));S(c);}return b<=31&&a.d0&1<<b?1:0;},K=a=>{let b;b=a.d0;b=((b&(-1431655766))>>>1|0)+(b&1431655765)|0;b=((b&(-858993460))>>>2|0)+(b&858993459)|0;b=((b&1886417008)>>>4|0)+(b&117901063)|0;b=((b&251662080)>>>8|0)+(b&983055)
|0;return ((b&2031616)>>>16|0)+(b&31)|0;},BU=a=>{return a.d0?0:1;},Ba=(a,b)=>{let c,d,e,f;if(b<0){c=new BN;d=U();Bh(I(d,E(86)),b);Ci(c,T(d));S(c);}if(b>31)return (-1);e=a.d0&(-1)<<b;if(!e)b=(-1);else if(!e)b=32;else{f=0;b=e<<16;if(b)f=16;else b=e;e=b<<8;if(!e)e=b;else f=f|8;b=e<<4;if(!b)b=e;else f=f|4;e=b<<2;if(!e)e=b;else f=f|2;if(e<<1)f=f|1;b=(32-f|0)-1|0;}return b;},BH=(a,b)=>{a.d0=a.d0|b.d0;},B$=(a,b)=>{a.d0=a.d0&b.d0;},Cc=(a,b)=>{a.d0=a.d0&(b.d0^(-1));},Bs=a=>{let b;b=new Z;b.d0=a.d0;return b;},Fe=(a,b)=>
{return b instanceof Z&&b.d0==a.d0?1:0;},Mp=a=>{return 1234^a.d0;};
function In(){let a=this;F.call(a);a.g5=0;a.hZ=0;a.hO=0;a.h1=null;a.gC=null;}
let DP=null,Ek=()=>{let b,c,d,e,f,g,h,i;if(DP===null){b=new In;b.g5=0;b.hZ=1;b.hO=1;b.h1=null;c=R(C4).eR;c.$clinit();d=EP(c);if(d===null){b=new C5;Y(b);S(b);}e=d.data.length;d=BE(!e?0:((e-1|0)/32|0)+1|0);f=d.data;g=0;h=f.length;if(g>h){b=new Ce;Y(b);S(b);}while(g<h){i=g+1|0;f[g]=(-1);g=i;}if(e>0){i=h-1|0;f[i]=f[i]&((-1)>>>(32-(e%32|0)|0)|0);}b.gC=HO(R(C4),d);DP=b;}return DP;},Hy=a=>{let b;b=a.gC;return HO(b.fV,b.gm.I());},Kg=()=>{DP=null;},Ce=H(Bv),D8=H(0),BC=H(Cb),He=(a,b)=>{let c,d,e;c=0;d=a;if(CK(d)>=b.dV)
{e=O(b);while(P(e)){if(!Cw(d,Q(e)))continue;c=1;}}else{d=Bp(d);b=b;while(d.bb()){if(BI(b,d.bc())){c=1;d.bC();}}}return c;},EM=(a,b)=>{let c,d;if(a===b)return 1;if(!DK(b,D8))return 0;c=b;if(a.bx()!=c.bx())return 0;d=c.ba();while(d.bb()){if(a.J(d.bc()))continue;else return 0;}return 1;},Jx=a=>{let b,c,d;b=0;c=a.ba();while(c.bb()){d=c.bc();if(d!==null)b=b+d.D()|0;}return b;},FS=H(BC);
function HU(){let a=this;FS.call(a);a.fV=null;a.gm=null;}
let Ke=(a,b,c)=>{a.fV=b;a.gm=c;},HO=(a,b)=>{let c=new HU();Ke(c,a,b);return c;},G4=(a,b)=>{let c,d,e,f,g;c=a.fV;d=b;c=c.eR;if(!(d!==null&&!(typeof d.constructor.$meta==='undefined'?1:0)&&Hd(d.constructor,c)?1:0))return 0;e=b.eN;f=e/32|0;g=1<<(e%32|0);return !(a.gm.data[f]&g)?0:1;},Lg=H(),CR=b=>{let c;DG(b);c=new GU;c.gh=b;return c;},Fr=H(BN),FF=H(0);
function ID(){F.call(this);this.fp=null;}
let MQ=a=>{a.fp=null;},Ii=()=>{let a=new ID();MQ(a);return a;},FX=(a,b)=>{if(b.C(a.fp))return;a.fp=b;b=new BF;Y(b);S(b);},Jo=a=>{return a.fp;},BF=H(Cz),BB=H(0),De=H(),NK=a=>{return null;},LX=a=>{return 0;},Ge=H(Cz),B_=H(0);
function G9(){let a=this;F.call(a);a.ga=0;a.gQ=0;a.gS=0;a.gD=0;a.gY=null;}
let P=a=>{return a.ga>=a.gS?0:1;},Q=a=>{let b,c,d;b=a.gQ;c=a.gY;if(b<c.d8){c=new Dd;Y(c);S(c);}d=a.ga;a.gD=d;a.ga=d+1|0;return c.bE(d);},LB=H(),DN=(b,c)=>{if(b<c)c=b;return c;},D0=(b,c)=>{if(b>c)c=b;return c;},Ku=H(),H5=(b,c)=>{if(b===null){b=new CC;Y(b);S(b);}if(b===R(Lo)){b=new Ce;Y(b);S(b);}if(c>=0)return LK(b.eR,c);b=new IM;Y(b);S(b);},LK=(b,c)=>{if(b.$meta.primitive){switch(b){};}return N(b,c);},CC=H(Bv),IM=H(Bv),Dd=H(Bv),DH=H(0);
function Du(){let a=this;F.call(a);a.ev=null;a.f0=null;}
let KP=a=>{let b;if(a.ev===null){b=new H6;b.gX=a;a.ev=b;}return a.ev;},Hi=(a,b)=>{let c,d,e,$$je;if(a===b)return 1;if(!DK(b,DH))return 0;c=b;if(a.bx()!=c.bx())return 0;a:{try{d=(a.c7()).ba();}catch($$e){$$je=Bb($$e);if($$je instanceof C5){break a;}else if($$je instanceof CC){break a;}else{throw $$e;}}b:{c:{try{while(d.bb()){e=d.bc();if(!c.cm(HF(e)))break b;if(!E5(MK(e),c.cn(HF(e))))break c;}}catch($$e){$$je=Bb($$e);if($$je instanceof C5){break a;}else if($$je instanceof CC){break a;}else{throw $$e;}}return 1;}try
{}catch($$e){$$je=Bb($$e);if($$je instanceof C5){break a;}else if($$je instanceof CC){break a;}else{throw $$e;}}return 0;}try{}catch($$e){$$je=Bb($$e);if($$je instanceof C5){break a;}else if($$je instanceof CC){break a;}else{throw $$e;}}return 0;}return 0;},KI=a=>{let b,c;b=0;c=(a.c7()).ba();while(c.bb()){b=b+LZ(c.bc())|0;}return b;};
function C6(){let a=this;Du.call(a);a.d1=0;a.d2=null;a.d7=0;a.hf=0.0;a.fM=0;}
let K2=(a,b)=>{return N(Db,b);},Gc=a=>{DB(a,16);},Bc=()=>{let a=new C6();Gc(a);return a;},DB=(a,b)=>{let c;if(b<0){c=new Ce;Y(c);S(c);}b=HC(b);a.d1=0;a.d2=a.c_(b);a.hf=0.75;Ib(a);},NV=a=>{let b=new C6();DB(b,a);return b;},HC=b=>{let c;if(b>=1073741824)return 1073741824;if(!b)return 16;c=b-1|0;b=c|c>>1;b=b|b>>2;b=b|b>>4;b=b|b>>8;return (b|b>>16)+1|0;},Ib=a=>{a.fM=a.d2.data.length*a.hf|0;},CW=(a,b)=>{return Ij(a,b)===null?0:1;},M5=a=>{let b;b=new Ic;b.hd=a;return b;},Ch=(a,b)=>{let c;c=Ij(a,b);if(c===null)return null;return c.eg;},Ij
=(a,b)=>{let c,d;if(b===null)c=D_(a);else{d=b.D();c=DL(a,b,d&(a.d2.data.length-1|0),d);}return c;},DL=(a,b,c,d)=>{let e;e=a.d2.data[c];while(e!==null&&!(e.eT==d&&Hg(b,e.ep))){e=e.d5;}return e;},D_=a=>{let b;b=a.d2.data[0];while(b!==null&&b.ep!==null){b=b.d5;}return b;},D6=a=>{return a.d1?0:1;},Ne=a=>{let b;if(a.ev===null){b=new It;b.g0=a;a.ev=b;}return a.ev;},W=(a,b,c)=>{let d,e,f;if(b===null){d=D_(a);if(d===null){a.d7=a.d7+1|0;d=H1(a,null,0,0);e=a.d1+1|0;a.d1=e;if(e>a.fM)FK(a);}}else{e=b.D();f=e&(a.d2.data.length
-1|0);d=DL(a,b,f,e);if(d===null){a.d7=a.d7+1|0;d=H1(a,b,f,e);e=a.d1+1|0;a.d1=e;if(e>a.fM)FK(a);}}b=d.eg;d.eg=c;return b;},H1=(a,b,c,d)=>{let e,f;e=Ju(b,d);f=a.d2.data;e.d5=f[c];f[c]=e;return e;},KK=(a,b)=>{let c,d,e,f,g,h,i;c=HC(!b?1:b<<1);d=a.c_(c);e=0;c=c-1|0;while(true){f=a.d2.data;if(e>=f.length)break;g=f[e];f[e]=null;while(g!==null){f=d.data;h=g.eT&c;i=g.d5;g.d5=f[h];f[h]=g;g=i;}e=e+1|0;}a.d2=d;Ib(a);},FK=a=>{KK(a,a.d2.data.length);},JQ=(a,b)=>{let c;c=Gm(a,b);if(c===null)return null;return c.eg;},Gm=(a,
b)=>{let c,d,e,f,g,h;a:{c=0;d=null;if(b===null){e=a.d2.data[0];while(e!==null){if(e.ep===null)break a;f=e.d5;d=e;e=f;}}else{g=b.D();h=a.d2.data;c=g&(h.length-1|0);e=h[c];while(e!==null&&!(e.eT==g&&Hg(b,e.ep))){f=e.d5;d=e;e=f;}}}if(e===null)return null;if(d!==null)d.d5=e.d5;else a.d2.data[c]=e.d5;a.d7=a.d7+1|0;a.d1=a.d1-1|0;return e;},Im=a=>{return a.d1;},Hg=(b,c)=>{return b!==c&&!b.C(c)?0:1;},G7=H(0);
function EU(){let a=this;C6.call(a);a.fC=0;a.es=null;a.eu=null;}
let K3=a=>{Gc(a);a.fC=0;a.es=null;},Ca=()=>{let a=new EU();K3(a);return a;},LU=(a,b)=>{return N(ET,b);},CN=(a,b)=>{let c,d;c=null;if(b===null)b=D_(a);else{d=b.D();b=DL(a,b,(d&2147483647)%a.d2.data.length|0,d);}if(b!==null){if(a.fC)HW(a,b,0);c=b.eg;}return c;},B8=(a,b,c)=>{let d,e,f,g,h,i,j,k,l,m;d=a;e=d.d1;f=a.fC;if(!a.d1){a.es=null;a.eu=null;}g=DX(b);h=g&2147483647;i=h%a.d2.data.length|0;j=b===null?D_(a):DL(a,b,i,g);if(j===null){a.d7=a.d7+1|0;k=a.d1+1|0;a.d1=k;if(k>a.fM){FK(d);i=h%a.d2.data.length|0;}l=new ET;HR(l,
b,g);l.eh=null;l.eb=null;m=a.d2.data;l.d5=m[i];m[i]=l;b=a.eu;if(b===null)a.es=l;else b.eh=l;l.eb=b;a.eu=l;j=l;}else if(f)HW(a,j,0);l=j.eg;j.eg=c;return l;},HW=(a,b,c)=>{let d,e;if(!c){d=b.eh;if(d===null)return;e=b.eb;if(e===null)a.es=d;else e.eh=d;d.eb=e;d=a.eu;if(d!==null)d.eh=b;b.eb=d;b.eh=null;a.eu=b;}else{e=b.eb;if(e===null)return;d=b.eh;if(d===null)a.eu=e;else d.eb=e;e.eh=d;d=a.es;if(d!==null)d.eb=b;b.eh=d;b.eb=null;a.es=b;}},IB=a=>{let b;if(a.ev===null){b=new IC;b.gx=a;b.g9=0;a.ev=b;}return a.ev;},Cv=
a=>{let b;if(a.f0===null){b=new GD;b.f5=a;b.hb=0;a.f0=b;}return a.f0;},M6=(a,b)=>{let c;c=Gm(a,b);if(c===null)return null;Iu(a,c);return c.eg;},KH=(a,b)=>{let c,d,e,f,g;c=b.eT;d=a.d2.data;e=c&(d.length-1|0);f=d[e];if(f===b)d[e]=b.d5;else{while(true){g=f.d5;if(g===b)break;f=g;}f.d5=b.d5;}a.d7=a.d7+1|0;a.d1=a.d1-1|0;Iu(a,b);},Iu=(a,b)=>{let c,d;c=b.eb;d=b.eh;if(c!==null){c.eh=d;if(d===null)a.eu=c;else d.eb=c;}else{a.es=d;if(d===null)a.eu=null;else d.eb=null;}};
function DQ(){let a=this;F.call(a);a.gI=0;a.gr=0;a.gR=Ec;a.fK=Ec;a.fG=0;}
let Eq=(a,b,c)=>{let d;if(b<0){d=new Ce;Ci(d,E(87));S(d);}if(c<0){d=new Ce;Ci(d,E(88));S(d);}if(b>c){d=new Ce;Ci(d,E(89));S(d);}if(c>64){d=new Ce;Ci(d,E(90));S(d);}a.gI=c;a.gr=b;a.fK=Ed((1<<b)-1|0);a.gR=LM(HT(Ed(1),c-b|0),Ed(1));a.fG=c?0:1;},Cr=(a,b)=>{let c=new DQ();Eq(c,a,b);return c;},B7=a=>{let b,c;b=a.fG?0:1;c=a.fK;a.fG=Gu(Dz(Dz(c,GE(c)),a.gR),Ec)?0:1;return b;},B9=a=>{let b,c,d,e,f,g,h,i,j,k;b=a.fK;if(!a.fG){c=Dz(b,GE(b));d=JG(b,c);a.fK=JE(d,MT(KN(KC(b,d),2),c));}e=BE(a.gr);f=0;g=a.gI;if(g>31){h=e.data;i
=0;while(i<g){if(Gu(Dz(b,HT(Ed(1),i)),Ec)){j=f+1|0;h[f]=i;f=j;}i=i+1|0;}return e;}h=e.data;j=Jc(b);i=0;while(i<g){if(j&1<<i){k=f+1|0;h[f]=i;f=k;}i=i+1|0;}return e;};
function CM(){BC.call(this);this.eF=null;}
let Km=a=>{Dg(a,Bc());},CJ=()=>{let a=new CM();Km(a);return a;},Dg=(a,b)=>{a.eF=b;},NR=a=>{let b=new CM();Dg(b,a);return b;},Bq=(a,b)=>{return a.eF.bS(b,a)!==null?0:1;},BP=(a,b)=>{return CW(a.eF,b);},CT=a=>{return D6(a.eF);},Bp=a=>{return (a.eF.dm()).ba();},Cw=(a,b)=>{return a.eF.dn(b)===null?0:1;},CK=a=>{return a.eF.d1;},E6=H(0),EG=H(CM),KZ=a=>{Dg(a,Ca());},B0=()=>{let a=new EG();KZ(a);return a;},Jl=(a,b)=>{let c,d;c=new EU;DB(c,b.bx()<6?11:b.bx()*2|0);c.fC=0;c.es=null;Dg(a,c);c=b.ba();d=a;while(c.bb()){Bq(d,
c.bc());}},Da=a=>{let b=new EG();Jl(b,a);return b;};
function Bo(){let a=this;De.call(a);a.g1=null;a.ei=null;}
let BO=(a,b,c)=>{a.g1=b;a.ei=c;},NY=a=>{return a.ei;},Bn=a=>{return a.ei.T()?0:1;},JI=a=>{let b,c,d;b=(a.ei.dm()).ba();while(b.bb()){c=b.bc();d=a.ei.cn(c);Cc(c.dT,d);}if(a.bi()!==null)E8(a.bi(),a.dp());};
function EY(){let a=this;Bo.call(a);a.fh=null;a.h0=null;}
let Nc=(a,b,c,d,e)=>{BO(a,b,c);a.fh=d;a.h0=e;},Iv=(a,b,c,d)=>{let e=new EY();Nc(e,a,b,c,d);return e;},LE=a=>{let b,c;b=a.fh.data.length;if(b==2)return 6.2;if(b==3)return 7.5;c=new DM;Y(c);S(c);},KR=a=>{let b,c,d,e;b=a.fh.data.length;if(b==2)c=E(48);else if(b==3)c=E(52);else if(b==4)c=E(91);else{c=U();I(Bh(I(c,E(92)),b),E(93));c=T(c);}d=DI(a.fh);e=U();I(I(I(e,c),E(66)),d);return T(e);},Gi=a=>{let b,c,d,e,f;b=CJ();c=a.fh.data;d=c.length;e=0;f=b;while(e<d){Bq(f,c[e]);e=e+1|0;}return b;},I5=(a,b)=>{let c,d;if(!(b instanceof EY))return 0;c
=b;b=Gi(a);d=Gi(c);if(!EM(b,d))return 0;b=a.ei;c=c.ei;return Hi(b,c);},NG=H(),Bz=b=>{let c;c=new Z;Bw(c,b);return c;},CE=H(Bo),ED=(a,b)=>{BO(a,b,Bc());},Kc=a=>{return;};
function C1(){let a=this;CE.call(a);a.hg=null;a.hv=null;a.h8=null;}
let D4=(a,b,c,d,e)=>{ED(a,b);a.hg=c;a.hv=d;a.h8=e;},Ea=(a,b,c,d)=>{let e=new C1();D4(e,a,b,c,d);return e;},K4=a=>{return a.hg;};
function Ik(){F.call(this);this.hn=null;}
let LW=(a,b,c)=>{let d;b=b;c=c;d=B1(b.bf(),c.bf());return d<0?(-1):d>0?1:b.ds()-c.ds()|0;},Lq=H(),Hc=null,EF=null,I6=null,F5=null,L8=null,L6=null,Hz=(b,c)=>{let d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t;if(c===null)c=FR;d=b;e=N(F,d.dV);f=e.data;Co(b,e);g=f.length;if(g){if(c===null)c=FR;h=N(F,g);i=1;j=e;while(i<g){k=0;while(true){l=j.data;m=l.length;if(k>=m)break;n=DN(m,k+i|0);o=k+(2*i|0)|0;p=DN(m,o);m=k;q=n;a:{b:{while(k!=n){if(q==p)break b;b=l[k];r=l[q];if(c.dt(b,r)>0){s=h.data;t=m+1|0;s[m]=r;q=q+1|0;}else{s=h.data;t
=m+1|0;s[m]=b;k=k+1|0;}m=t;}while(true){if(q>=p)break a;s=h.data;t=m+1|0;k=q+1|0;s[m]=l[q];m=t;q=k;}}while(true){if(k>=n)break a;s=h.data;t=m+1|0;q=k+1|0;s[m]=l[k];m=t;k=q;}}k=o;}i=i*2|0;s=j;j=h;h=s;}c:{if(j!==e){m=0;while(true){e=j.data;if(m>=e.length)break c;h.data[m]=e[m];m=m+1|0;}}}}m=0;while(m<g){b=f[m];Eu(d,m);d.ed.data[m]=b;m=m+1|0;}},F2=b=>{let c;DG(b);c=new H9;c.gl=b;return c;},J5=()=>{Hc=new F_;EF=new F9;I6=new F$;F5=new F7;L8=new F8;L6=new Iz;};
function B4(){let a=this;Bo.call(a);a.er=null;a.gt=0;a.gu=0;}
let Dj=(a,b,c,d,e,f)=>{BO(a,b,f);a.er=c;a.gt=d;a.gu=e;},Gl=a=>{if(a.er.dV!=4)return E(94);return E(95);},Jm=a=>{let b,c,d,e;if(a.er.dV<=6){b=Gl(a);c=a.ds();d=U();Bh(I(I(I(d,E(96)),b),E(97)),c);return T(d);}b=Gl(a);c=a.er.dV;e=a.ds();d=U();Bh(I(Bh(B6(I(I(d,E(96)),b),32),c),E(97)),e);return T(d);},E$=a=>{let b,c;b=4.5;c=a.er.dV;if(c>=10)b=4.8;if(c>=8)b=b+0.2;else if(c>=6)b=b+0.1;return b;},I_=a=>{let b,c,d,e,f,g;b=a.er;c=N(BD,b.dV);Co(b,c);b=Jm(a);d=CF(c);e=a.gt;f=a.gu;g=U();Bh(I(Bh(I(I(I(I(g,b),E(66)),d),E(98)),
e),E(79)),f);return T(g);},FJ=(a,b)=>{let c,d;if(b===null)return 0;if(!Bg(CY(b),CY(a)))return 0;c=b;b=a.er;d=b.dV;c=c.er;if(d!=c.dV)return 0;return ER(b,c);},IS=a=>{let b,c;b=0;c=O(a.er);while(P(c)){b=b^Eo(Q(c));}return b;};
function GB(){let a=this;C1.call(a);a.hK=null;a.hw=null;a.h2=null;}
function GA(){let a=this;CE.call(a);a.fx=null;a.gG=null;a.gF=null;a.gE=0;}
let Ng=a=>{let b,c;if(a.gE)Bx(a.gF,a.fx);else Bx(a.gG,a.fx);b=0;while(b<9){c=0;while(c<9){GI(Bf(a.fx,c,b));c=c+1|0;}b=b+1|0;}},Kv=a=>{return E(80);};
function GN(){let a=this;CE.call(a);a.g6=null;a.g3=null;}
let KV=a=>{return E(99);},IX=a=>{Bx(a.g3,a.g6);};
function C9(){let a=this;De.call(a);a.f_=null;a.g8=null;a.e8=null;a.fE=0;}
let Hs=(a,b,c,d,e)=>{a.f_=b;a.g8=c;a.e8=d;a.fE=e;},JA=a=>{return a.e8;},IQ=a=>{E8(a.e8,a.fE);},Kd=(a,b)=>{let c,d,e;if(!(b instanceof C9))return 0;a:{c=b;if(Bg(a.e8,c.e8)){b=a.f_;d=c.f_;if(Bg(b,d)&&a.fE==c.fE){e=1;break a;}}e=0;}return e;},HQ=H(C9),Na=a=>{return 2.3;},Ma=H(),Dv=(b,c)=>{let d,e,f,g;b=b.data;d=new Z;e=b.length;f=0;while(true){if(f>=e){if(K(d)==c)return d;return null;}g=b[f];if(K(g)<=1)break;BH(d,g);f=f+1|0;}return null;},K5=(b,c)=>{let d,e,f,g;b=b.data;d=new Z;e=b.length;f=0;while(true){if(f>=
e){if(K(d)==c)return d;return null;}g=b[f];BH(d,g);if(!K(g))break;f=f+1|0;}return null;},Gq=H(),FR=null,Le=(a,b,c)=>{b=b;c=c;return B1(b.e0,c.e0);},Nf=()=>{FR=new Gq;},CU=H(0);
function BS(){let a=this;Bo.call(a);a.eq=0;a.eC=0;}
let Dc=(a,b,c,d,e)=>{BO(a,b,c);a.eq=d;a.eC=e;},DS=(a,b)=>{let c,d,e,f,g,h,i;c=V();d=CJ();e=V();J(e,b);f=d;d=c;while(!Bj(e)){g=V();h=O(e);e=g;while(P(h)){i=Q(h);if(!BP(f,i)){Bq(f,i);J(d,i);BW(e,i.d4);}}e=g;}return c;},MA=(a,b,c)=>{let d,e;d=B0();e=(a.dy()).ba();while(e.bb()){MH(a,b,c,d,e.bc());}return d;},MH=(a,b,c,d,e)=>{let f,g,h,i,j,k,l,m,n,o,p,q,r,s,t;f=CJ();g=V();J(g,e);h=f;i=a instanceof Fx;j=a instanceof Ef;e=a;f=d;while(!Bj(g)){k=V();g=O(g);l=k;while(P(g)){m=Q(g);if(!BP(h,m)){Bq(h,m);n=m.eP;if(n===null)
{if(i)n=C0;else if(j)n=Ev(e.fS);}a:{if(m.dZ&&n!==null){o=m.dU;if(n!==C0?0:1){p=Bf(c,o.dY,o.dX);q=Bf(b,o.dY,o.dX);r=1;while(r<=9){if(X(q,r)&&!X(p,r))Bq(f,Bt(p,r,0));r=r+1|0;}}else{b:{Fu();switch(IO.data[n.eN]){case 1:break;case 2:d=R(Br);break b;case 3:d=R(Bu);break b;default:d=null;break b;}d=R(Bk);}s=DJ(c,d,o);t=0;while(true){if(t>=9)break a;p=s.S(t);if(X(Bf(b,p.dY,p.dX),m.dW)&&!X(p,m.dW))Bq(f,Bt(p,m.dW,0));t=t+1|0;}}}}BW(l,m.d4);}}g=k;}},C_=a=>{return a.g1;},JY=a=>{let b;b=a.dA();if(b!==null&&b.dZ)return b.dU;return null;},M7
=a=>{let b;b=a.dA();if(b!==null&&b.dZ)return b.dW;return 0;},Dq=a=>{let b,c,d,e;b=0.0;c=4;d=D$(a)-2|0;e=0;while(d>c){b=b+0.1;c=e?(c*4|0)/3|0:(c*3|0)/2|0;e=e?0:1;}return b;},CI=(a,b)=>{let c,d,e,f,g;c=CJ();d=V();J(d,b);b=c;while(!Bj(d)){e=V();f=O(d);d=e;while(P(f)){g=Q(f);if(!BP(b,g)){Bq(b,g);BW(d,g.d4);}}d=e;}return CK(b);},D$=a=>{let b,c,d,e,f,g,h,i;b=a.dC();c=0;d=CJ();e=(a.dy()).ba();f=d;while(e.bb()){g=O(DS(a,e.bc()));while(P(g)){d=Q(g);h=d.eZ;if(h!==null){i=new Fs;i.eH=h;if(!BP(f,i)){c=c+D$(d.eZ)|0;Bq(f,
i);}}}}return b+c|0;},M3=(a,b)=>{let c,d;if(!(b instanceof BS))return 0;c=b;d=a.ei;c=c.ei;return Hi(d,c);},I$=a=>{return KI(a.ei);};
function F0(){let a=this;Bo.call(a);a.fa=0;a.eG=null;a.eI=null;a.ew=null;a.fF=0;}
let MP=a=>{if(!a.fa)return 4.2;return 4.4;},JZ=(a,b,c)=>{let d,e,f,g,h,i;d=V();c=a.eG;e=Bf(b,c.dY,c.dX);c=a.eI;f=Bf(b,c.dY,c.dX);c=a.ew;g=Bf(b,c.dY,c.dX);h=1;i=d;while(h<=9){if(X(e,h)&&!X(a.eG,h))J(i,Bt(a.eG,h,0));if(X(f,h)&&!X(a.eI,h))J(i,Bt(a.eI,h,0));if(X(g,h)&&!X(a.ew,h))J(i,Bt(a.ew,h,0));h=h+1|0;}return d;},MS=(a,b)=>{let c,d;if(!(b instanceof F0))return 0;c=b;if(a.fa!=c.fa)return 0;if(a.eG===c.eG&&a.fF==c.fF){b=a.eI;d=c.eI;if(b!==d&&b!==c.ew)return 0;b=a.ew;if(b!==d&&b!==c.ew)return 0;return 1;}return 0;},Ks
=a=>{let b,c,d;b=U();L(b,!a.fa?E(35):E(37));L(b,E(66));c=N(BD,3);d=c.data;d[0]=a.eG;d[1]=a.eI;d[2]=a.ew;L(b,CF(c));L(b,E(100));Bh(b,a.fF);return T(b);},Cd=H(Bo);
function HD(){let a=this;Cd.call(a);a.gs=null;a.hD=null;}
let KB=a=>{return 5.6;},Nl=a=>{let b,c;b=Do(a.gs);c=U();I(I(c,E(101)),b);return T(c);};
function Hr(){let a=this;Cd.call(a);a.g$=null;a.gH=0;}
let Mq=a=>{return 5.7;},J4=a=>{let b,c,d;b=DI(a.g$);c=a.gH;d=U();Bh(I(I(I(d,E(102)),b),E(98)),c);return T(d);};
function IE(){let a=this;Cd.call(a);a.gV=null;a.gT=null;a.hG=null;a.hm=null;a.g4=0;a.hz=null;}
let NN=a=>{return 5.7;},I4=a=>{let b,c,d,e;b=Do(a.gV);c=Do(a.gT);d=a.g4;e=U();Bh(I(I(B6(I(I(e,E(103)),b),44),c),E(98)),d);return T(e);};
function IN(){let a=this;Cd.call(a);a.g7=null;a.h6=null;a.hr=null;a.hA=null;a.fZ=null;a.hk=null;}
let MZ=a=>{return 5.7+(K(a.fZ)-1|0)*0.1;},Jh=a=>{let b,c,d,e,f,g,h,i,j;b=DI(a.g7);c=a.fZ;d=BE(K(c)).data;e=0;f=Ba(c,0);while(f>=0){g=e+1|0;d[e]=f;f=Ba(c,f+1|0);e=g;}h=U();f=0;i=d.length;e=i-1|0;while(f<i){if(f>0&&f==e)L(h,E(79));else if(f>0)L(h,E(79));Bh(h,d[f]);f=f+1|0;}h=T(h);j=U();I(I(I(I(j,E(104)),b),E(98)),h);return T(j);};
function Ip(){C9.call(this);this.gK=0;}
let JS=a=>{if(a.gK)return 1.0;if(!(a.g8 instanceof Bk))return 1.5;return 1.2;};
function Ee(){let a=this;Bo.call(a);a.e_=null;a.eK=0;a.hP=null;a.ef=null;}
let Ls=(a,b,c,d,e,f,g)=>{BO(a,b,f);a.e_=c;a.eK=d;a.hP=e;a.ef=g;},Iq=(a,b,c,d,e,f)=>{let g=new Ee();Ls(g,a,b,c,d,e,f);return g;},NL=a=>{let b,c;b=a.ef.data;c=b.length/2|0;if(c==1){if(!(b[0] instanceof Bk))return 2.8;return 2.6;}if(c==2)return 3.2;if(c!=3)return 5.2;return 3.8;},LR=(a,b,c)=>{let d,e,f,g,h,i,j,k;d=V();e=0;f=d;while(e<a.ef.data.length){g=0;while(g<9){h=a.ef.data[e].S(g);if(X(Bf(b,h.dY,h.dX),a.eK)&&!X(h,a.eK)){i=0;j=1;while(j<a.ef.data.length){k=0;while(k<9){if(Bg(a.ef.data[j].S(k),h))i=1;k=k+1|
0;}j=j+2|0;}if(!i)J(f,Bt(h,a.eK,0));}g=g+1|0;}e=e+2|0;}return d;},Ll=a=>{let b,c,d,e,f;b=U();c=a.ef.data;d=c.length/2|0;L(b,d==1?(!(c[0] instanceof Bk)?E(105):E(106)):d!=2?(d==3?E(31):d!=4?null:E(42)):!(c[0] instanceof Bk)&&!(c[1] instanceof Bk)?E(26):E(107));L(b,E(66));L(b,CF(a.e_));L(b,E(66));Bh(b,a.eK);c=a.ef;if(c!==null){e=c.data.length;if(e==2){L(b,E(108));L(b,a.ef.data[0].g());L(b,E(109));L(b,a.ef.data[1].g());}else if(e>=4&&!(e%2|0)){d=e/2|0;f=U();B6(Bh(I(f,E(108)),d),32);L(b,T(f));L(b,a.ef.data[0].g());d
=a.ef.data.length/2|0;f=U();B6(Bh(I(f,E(110)),d),32);L(b,T(f));L(b,a.ef.data[1].g());L(b,E(111));}}return T(b);},Jj=(a,b)=>{let c,d;if(!(b instanceof Ee))return 0;c=b;if(a.eK!=c.eK)return 0;d=a.e_;if(d.data.length!=c.e_.data.length)return 0;b=CR(d);c=CR(c.e_);return ER(b,c);};
function Gz(){B4.call(this);this.hV=null;}
let LG=a=>{return 1;};
function If(){let a=this;B4.call(a);a.hN=null;a.hY=0;}
let J3=a=>{return 2;};
function IA(){let a=this;B4.call(a);a.hB=null;a.hC=null;a.hM=0;a.hu=0;a.hJ=null;}
let KJ=a=>{return 4;},EJ=H(BC),F_=H(EJ),I7=a=>{return F5;},Ft=H(Du),F9=H(Ft),JP=a=>{return Hc;},LO=a=>{return 0;},IT=(a,b)=>{return null;},ND=a=>{return 1;},KO=(a,b)=>{return 0;},Di=H(B3),F$=H(Di),F7=H(),J6=a=>{return 0;},Lr=a=>{let b;b=new Dy;Y(b);S(b);},I0=a=>{let b;b=new CQ;Y(b);S(b);},FU=H(0),F8=H(),Iz=H();
function Ix(){let a=this;Bo.call(a);a.f2=null;a.e2=null;a.hs=null;a.gq=null;}
let Kp=a=>{let b;b=a.e2.data.length;if(b==2)return 3.0;if(b!=3)return 5.0;return 3.6;},LJ=(a,b,c)=>{let d,e,f,g,h,i,j,k,l,m;d=V();e=new Z;f=0;while(true){g=a.e2.data;if(f>=g.length)break;Bw(e,g[f]);f=f+1|0;}g=a.f2.data;h=g.length;i=0;j=d;while(i<h){k=g[i];l=Bf(b,k.dY,k.dX);m=1;while(m<=9){if(X(l,m)&&!Bd(e,m))J(j,Bt(k,m,0));m=m+1|0;}i=i+1|0;}return d;},Kt=a=>{let b,c,d,e,f;b=U();c=N(BX,3).data;c[0]=E(112);c[1]=E(113);c[2]=E(114);d=c[a.e2.data.length-2|0];e=U();I(I(e,E(115)),d);L(b,T(e));L(b,E(66));c=a.f2;if(c.data.length
>4)L(b,E(116));else L(b,CF(c));L(b,E(66));f=0;while(f<a.e2.data.length){if(f>0)L(b,E(7));L(b,DZ(a.e2.data[f]));f=f+1|0;}L(b,E(108));L(b,a.gq.g());return T(b);};
function Ep(){let a=this;Bo.call(a);a.fr=null;a.gW=null;a.e9=0;a.ht=null;a.hl=null;a.fl=null;}
let MJ=a=>{return a.gW;},M2=a=>{return a.e9;},Mv=a=>{return 1;},MV=a=>{if(!(a.fl.data[0] instanceof Bk))return 1.9;return 1.7;},L1=a=>{let b;b=U();L(b,!(a.fl.data[0] instanceof Bk)?E(117):E(14));L(b,E(66));L(b,CF(a.fr));L(b,E(66));Bh(b,a.e9);L(b,E(118));L(b,a.fl.data[0].g());L(b,E(108));L(b,a.fl.data[1].g());return T(b);},L0=(a,b)=>{let c,d;if(!(b instanceof Ep))return 0;c=b;if(a.e9!=c.e9)return 0;d=a.fr;if(d.data.length!=c.fr.data.length)return 0;b=CR(d);c=CR(c.fr);return ER(b,c);};
function G$(){let a=this;Bo.call(a);a.gA=null;a.ex=null;a.hp=null;a.fQ=null;}
let JW=a=>{let b;b=a.ex.data.length;if(b==2)return 3.4;if(b!=3)return 5.4;return 4.0;},Ky=(a,b,c)=>{let d,e,f,g,h,i,j,k;d=V();e=new Z;f=0;while(true){g=a.ex.data;if(f>=g.length)break;BH(e,BA(a.fQ,g[f]));f=f+1|0;}f=0;h=d;while(f<9){a:{if(!Bd(e,f)){i=a.fQ.S(f);j=Bf(b,i.dY,i.dX);k=0;while(true){g=a.ex.data;if(k>=g.length)break a;if(X(j,g[k]))J(h,Bt(i,a.ex.data[k],0));k=k+1|0;}}}f=f+1|0;}return d;},M9=a=>{let b,c,d,e,f;b=U();c=N(BX,3).data;c[0]=E(112);c[1]=E(113);c[2]=E(114);d=c[a.ex.data.length-2|0];e=U();I(I(e,
E(119)),d);L(b,T(e));L(b,E(66));c=a.gA;if(c.data.length>4)L(b,E(116));else L(b,CF(c));L(b,E(66));f=0;while(f<a.ex.data.length){if(f>0)L(b,E(7));L(b,DZ(a.ex.data[f]));f=f+1|0;}L(b,E(108));L(b,a.fQ.g());return T(b);};
function Hu(){let a=this;Bo.call(a);a.gL=null;a.fi=null;a.gZ=null;a.gN=0;a.hW=null;a.hU=null;a.hj=null;}
let Jt=a=>{return a.gZ;},Jp=a=>{return a.gN;},M$=a=>{return 1;},I2=a=>{let b;b=a.fi.data.length;if(b==2)return 2.0;if(b!=3)return 4.3;return 2.5;},LF=a=>{let b,c,d,e,f;b=U();c=N(BX,3).data;c[0]=E(112);c[1]=E(113);c[2]=E(114);d=c[a.fi.data.length-2|0];e=U();I(I(e,E(120)),d);L(b,T(e));L(b,E(66));c=a.gL;if(c.data.length>4)L(b,E(116));else L(b,CF(c));L(b,E(66));f=0;while(f<a.fi.data.length){if(f>0)L(b,E(7));L(b,DZ(a.fi.data[f]));f=f+1|0;}L(b,E(108));L(b,a.hj.g());return T(b);};
function Er(){let a=this;B4.call(a);a.hE=null;a.hF=null;a.hT=null;a.f3=null;a.fY=null;a.fR=null;}
let NH=(a,b,c,d,e,f,g,h,i,j,k,l)=>{Dj(a,b,c,d,e,f);a.hE=g;a.hF=h;a.hT=i;a.f3=j;a.fY=k;a.fR=l;},Lj=(a,b,c,d,e,f,g,h,i,j,k)=>{let l=new Er();NH(l,a,b,c,d,e,f,g,h,i,j,k);return l;},Lc=a=>{let b;b=(a.fR.data.length-1|0)*0.1;return E$(a)+b;},MD=a=>{return 3;},NB=(a,b)=>{let c,d,e,f,g;if(!(b instanceof Er))return 0;if(!FJ(a,b))return 0;c=b;if(!Bg(a.f3,c.f3))return 0;d=a.fR.data;e=d.length;f=c.fR.data;if(e!=f.length)return 0;g=0;while(true){if(g>=e){e=0;while(true){d=a.fY.data;if(e>=d.length)break;if(!Bg(d[e],c.fY.data[e]))return 0;e
=e+1|0;}return 1;}if(d[g]!=f[g])break;g=g+1|0;}return 0;};
function FV(){let a=this;B4.call(a);a.h4=null;a.h5=null;a.ho=null;a.gf=null;a.gg=null;a.fu=null;}
let I8=a=>{let b;b=(a.fu.data.length-1|0)*0.1;return E$(a)+b;},Lx=a=>{return 3;},Lv=(a,b)=>{let c,d,e,f,g;if(!(b instanceof FV))return 0;if(!FJ(a,b))return 0;c=b;if(!Bg(a.gf,c.gf))return 0;if(!Fe(a.gg,c.gg))return 0;d=a.fu.data;e=d.length;f=c.fu.data;if(e!=f.length)return 0;g=0;while(g<e){if(d[g]!=f[g])return 0;g=g+1|0;}return 1;};
function GU(){B3.call(this);this.gh=null;}
let IY=(a,b)=>{return a.gh.data[b];},K$=a=>{return a.gh.data.length;},Gb=H(0);
function FC(){let a=this;F.call(a);a.ep=null;a.eg=null;}
let HF=a=>{return a.ep;},MK=a=>{return a.eg;},LZ=a=>{return DX(a.ep)^DX(a.eg);};
function Db(){let a=this;FC.call(a);a.eT=0;a.d5=null;}
let HR=(a,b,c)=>{let d;d=null;a.ep=b;a.eg=d;a.eT=c;},Ju=(a,b)=>{let c=new Db();HR(c,a,b);return c;};
function ET(){let a=this;Db.call(a);a.eh=null;a.eb=null;}
function F4(){F.call(this);this.hx=null;}
let Mk=(a,b,c)=>{let d,e;b=b;c=c;d=B1(b.bf(),c.bf());if(d<0)d=(-1);else if(d>0)d=1;else{d=D$(b);e=D$(c);d=d!=e?d-e|0:b.dE()-c.dE()|0;}return d;};
function F6(){B3.call(this);this.f8=null;}
let Lh=(a,b)=>{return a.f8.bE(b);},Lb=a=>{return a.f8.bx();};
function Cj(){let a=this;F.call(a);a.dU=null;a.dW=0;a.dZ=0;a.d4=null;a.fo=null;a.eP=null;a.eZ=null;}
let HB=(a,b,c,d)=>{a.d4=Cf(1);a.dU=b;a.dW=c;a.dZ=d;a.fo=null;a.eP=null;a.eZ=null;},Bt=(a,b,c)=>{let d=new Cj();HB(d,a,b,c);return d;},LN=(a,b,c,d,e,f,g)=>{let h;h=Cf(1);a.d4=h;a.dU=b;a.dW=c;a.dZ=d;J(h,e);a.eP=f;a.fo=g;a.eZ=null;},DT=(a,b,c,d,e,f)=>{let g=new Cj();LN(g,a,b,c,d,e,f);return g;},JM=a=>{Dn(a.dU,a.dW);},Dr=(a,b)=>{let c;if(!(b instanceof Cj))return 0;c=b;return Bg(a.dU,c.dU)&&a.dW==c.dW&&a.dZ==c.dZ?1:0;},HG=a=>{let b;b=a.dU;return (((((b.dX*9|0)+b.dY|0)*9|0)+a.dW|0)*2|0)+(!a.dZ?0:1)|0;},Ck=a=>{let b,
c,d;b=Do(a.dU);c=a.dW;d=U();Bh(B6(I(d,b),46),c);return T(d);};
function Hx(){BC.call(this);this.e1=null;}
let Lw=a=>{a.e1=Ca();},BG=()=>{let a=new Hx();Lw(a);return a;},BK=(a,b)=>{return B8(a.e1,b,b)===null?0:1;},Cl=(a,b)=>{return CW(a.e1,b);},Cn=(a,b)=>{return CN(a.e1,b);},CA=a=>{return Hn(IB(a.e1));},KU=a=>{return a.e1.d1;};
function Fx(){let a=this;BS.call(a);a.g_=null;a.fj=null;}
let JJ=a=>{return F2(Cv(a.fj));},Nj=a=>{let b,c,d,e;b=0;c=CG(Cv(a.fj));d=c;e=c;while(BY(d)){b=b+CI(a,CH(e))|0;}return b;},Jk=a=>{return 5;},LQ=a=>{let b;b=a;return Ey(C_(b))+Dq(b);},Jv=a=>{return CH(CG(Cv(a.fj)));},I1=a=>{let b,c,d,e,f;b=GO(C_(a),a);if(b===null)b=E(121);c=CH(CG(Cv(a.fj)));d=Do(a.g_);e=Ck(c);c=!c.dZ?E(122):E(123);f=U();I(I(I(I(I(I(f,b),E(66)),d),E(124)),e),c);return T(f);},H0=H(0),Kr=H(),E2=H(B3),Ig=(a,b,c)=>{let d,e,f;if(b<0){c=new BN;Y(c);S(c);}d=FG(a,b);Hh(d);e=new Fm;e.gd=c;c=d.eS;e.eD=c;f
=d.ey;e.ek=f;if(c!==null)c.ek=e;else d.eL.fg=e;if(f!==null)f.eD=e;else d.eL.fv=e;d.eS=e;c=d.eL;c.eA=c.eA+1|0;b=c.d8+1|0;c.d8=b;d.fz=b;d.fO=null;},CO=(a,b)=>{let c,d,e,f,g,h;if(b<0){c=new BN;Y(c);S(c);}c=FG(a,b);d=E7(c);e=c.fO;if(e===null){c=new CQ;Y(c);S(c);}f=c.eL;g=e.eD;if(g===null)f.fg=e.ek;else g.ek=e.ek;h=e.ek;if(h===null)f.fv=g;else h.eD=g;f.eA=f.eA-1|0;f.d8=f.d8+1|0;f=c.eS;if(e===f){c.eS=!Id(c)?null:c.ey.eD;c.fq=c.fq-1|0;}else if(e===c.ey)c.ey=!(f===null?0:1)?null:f.ek;c.fz=c.eL.d8;c.fO=null;return d;},Gh
=H(0),H_=H(0);
function Fy(){let a=this;E2.call(a);a.fg=null;a.fv=null;a.eA=0;}
let L5=(a,b)=>{let c,d,e,f;c=CA(b);d=null;e=c;c=c;while(BY(e)){f=new Fm;f.gd=Cp(c);f.eD=d;if(d!==null)d.ek=f;else a.fg=f;a.eA=a.eA+1|0;d=f;}a.fv=d;},CX=a=>{let b=new Fy();L5(b,a);return b;},MY=a=>{return a.eA;},FG=(a,b)=>{let c,d,e,f;if(b<0){c=new BN;Y(c);S(c);}d=a.eA;if(b<=(d/2|0)){e=a.fg;f=0;while(f<b){e=e.ek;f=f+1|0;}return Fq(a,e,e===null?null:e.eD,b);}if(b>d){c=new BN;Y(c);S(c);}c=a.fv;f=b;while(f<d){c=c.eD;f=f+1|0;}return Fq(a,c===null?null:c.ek,c,b);};
function GG(){let a=this;BS.call(a);a.eE=null;a.eW=null;a.e7=null;a.fy=0;a.gc=0;a.fJ=0;}
let LS=(a,b,c,d,e,f,g,h)=>{Dc(a,b,c,1,1);a.fJ=(-1);a.eE=d;a.eW=e;a.e7=f;a.fy=g;a.gc=h;},Gw=(a,b,c,d,e,f,g)=>{let h=new GG();LS(h,a,b,c,d,e,f,g);return h;},MM=a=>{let b,c,d;b=Cf(2);c=a.eW;d=b;J(d,c);J(d,a.e7);return b;},LL=a=>{let b,c;if(a.fJ<0){b=a.eW;c=a;a.fJ=CI(c,b)+CI(c,a.e7)|0;}return a.fJ;},Kq=a=>{if(!a.fy)return 1;return 7;},NI=a=>{let b;b=a;return Ey(C_(b))+Dq(b);},J1=a=>{let b,c;if(!a.gc&&!a.fy)return a.eW;b=new Cj;c=a.eE;HB(b,c.dU,c.dW,c.dZ?0:1);return b;},Mi=a=>{let b,c,d,e;if(a.gc){b=Ck(a.eE);c=!a.eE.dZ
?E(122):E(123);d=Ck(a.e7);e=U();I(I(I(I(I(I(e,E(125)),b),c),E(124)),d),E(126));return T(e);}if(!a.fy){b=Ck(a.eE);c=Ck(a.eW);d=!a.eW.dZ?E(122):E(123);e=U();I(I(I(I(I(e,E(127)),b),E(128)),c),d);return T(e);}b=Ck(a.eE);c=!a.eE.dZ?E(122):E(123);d=Ck(a.e7);e=U();I(I(I(I(I(I(e,E(129)),b),c),E(124)),d),E(126));return T(e);};
function Ef(){let a=this;BS.call(a);a.fS=null;a.gB=0;a.ff=null;}
let LC=a=>{let b,c,d,e;b=0;c=CG(Cv(a.ff));d=c;e=c;while(BY(d)){b=b+CI(a,CH(e))|0;}return b;},Kx=a=>{return F2(Cv(a.ff));},Ms=a=>{return 6;},MI=a=>{let b;b=a;return Ey(C_(b))+Dq(b);},L$=a=>{return CH(CG(Cv(a.ff)));},J0=a=>{let b,c,d,e,f,g;b=GO(C_(a),a);if(b===null)b=E(130);c=CH(CG(Cv(a.ff)));d=a.gB;e=a.fS.g();f=Ck(c);c=!c.dZ?E(122):E(123);g=U();I(I(I(I(I(Bh(I(I(g,b),E(66)),d),E(108)),e),E(124)),f),c);return T(g);};
function HL(){let a=this;BS.call(a);a.go=null;a.f6=null;a.fD=0;}
let Hk=a=>{let b,c,d,e;b=B0();c=a.f6;d=b;while(!Bj(c.d4)){c=Bl(c.d4,0);Bq(d,c.dU);}e=N(BD,CK(d));Co(b,e);return e;},IR=a=>{let b;if(a.fD<0){b=a.go;a.fD=CI(a,b);}return a.fD;},Jn=a=>{let b,c,d;b=Cf(2);c=a.go;d=b;J(d,c);J(d,a.f6);return b;},I9=a=>{let b;b=a.eq;if(b&&a.eC)return 4;if(!b)return 2;return 3;},L3=a=>{return (a.eq&&a.eC?7.0:6.5)+Dq(a);},LY=a=>{return null;},Nd=a=>{let b,c,d;b=a.eC&&a.eq?E(131):a.eq?E(132):(Hk(a)).data.length!=4?E(133):E(134);c=DI(Hk(a));d=U();I(I(I(d,b),E(66)),c);return T(d);};
function Hw(){let a=this;BS.call(a);a.et=null;a.fB=0;}
let J$=a=>{let b;if(a.fB<0){b=a.et;a.fB=CI(a,b);}return a.fB;},Ln=a=>{let b,c;b=a.et;c=new Ia;c.gy=b;return c;},KF=a=>{let b;b=a.eq;if(b&&a.eC)return 4;if(!b)return 2;return 3;},KX=a=>{return (a.eq&&a.eC?7.0:6.6)+Dq(a);},NO=a=>{let b;b=a.et;if(!b.dZ)return null;return b.dU;},JD=a=>{return a.et.dW;},JH=a=>{return a.et;},Nb=a=>{let b,c,d,e;if(a.eC&&a.eq)b=E(135);else if(a.eq)b=E(136);else{b=a.et;b=CI(a,b)!=6?E(137):E(138);}c=Ck(a.et);d=!a.et.dZ?E(122):E(123);e=U();I(I(I(I(e,b),E(66)),c),d);return T(e);},Cu=H(Dw),C0
=null,D7=null,D5=null,DC=null,G1=null,G8=null,Go=()=>{return G8.I();},Jq=()=>{let b,c,d;b=new Cu;CV(b,E(17),0);C0=b;b=new Cu;CV(b,E(139),1);D7=b;b=new Cu;CV(b,E(140),2);D5=b;b=new Cu;CV(b,E(141),3);DC=b;b=new Cu;CV(b,E(142),4);G1=b;c=N(Cu,5);d=c.data;d[0]=C0;d[1]=D7;d[2]=D5;d[3]=DC;d[4]=b;G8=c;};
function GH(){let a=this;F.call(a);a.gO=null;a.gz=null;a.hc=null;a.gw=null;a.hR=null;}
let La=(a,b,c,d,e,f)=>{a.gO=c;a.gz=d;a.hc=e;a.gw=f;a.hR=b;},M0=(a,b,c,d,e)=>{let f=new GH();La(f,a,b,c,d,e);return f;},J7=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n;a:{c=b;d=c.dN(a.gO,a.gz);if(!d.T()){e=null;if(c instanceof BS)e=c;f=c.ei;g=(f.dm()).ba();while(true){if(!g.bb())break a;h=g.bc();i=f.cn(h);j=Ba(i,0);while(j!=(-1)){k=G1;l=new Cj;m=c.g();l.d4=Cf(1);l.dU=h;l.dW=j;l.dZ=0;l.eP=k;l.fo=m;l.eZ=e;k=d.ba();while(k.bb()){m=k.bc();n=Cn(a.hc,m);J(l.d4,n);}J(a.gw,l);j=Ba(i,j+1|0);}}}}};
function Fm(){let a=this;F.call(a);a.gd=null;a.ek=null;a.eD=null;}
function It(){BC.call(this);this.g0=null;}
let IW=a=>{let b;b=new Gs;Ej(b,a.g0);return b;},LH=H(),Eh=null,Il=H(0),GR=H(0),H3=H(0),Fg=H();
function EQ(){Fg.call(this);this.h9=null;}
function EN(){let a=this;EQ.call(a);a.hQ=0;a.hL=null;a.h$=null;a.h3=null;}
let E1=H(EN),Gx=H(E1),CD=(a,b)=>{if(b===null)b=E(2);Kf(D9(b));},Kl=H();
function C8(){let a=this;F.call(a);a.fA=0;a.fI=0;a.fb=null;a.eJ=null;a.f9=null;a.eY=null;}
let Ej=(a,b)=>{a.eY=b;a.fI=b.d7;a.fb=null;},NQ=a=>{let b=new C8();Ej(b,a);return b;},GP=a=>{let b,c;if(a.fb!==null)return 1;while(true){b=a.fA;c=a.eY.d2.data;if(b>=c.length)break;if(c[b]!==null)return 1;a.fA=b+1|0;}return 0;},IL=a=>{let b;if(a.fI==a.eY.d7)return;b=new Dd;Y(b);S(b);},HM=a=>{let b,c,d,e;IL(a);if(!GP(a)){b=new Dy;Y(b);S(b);}b=a.fb;if(b!==null){c=a.eJ;if(c!==null)a.f9=c;a.eJ=b;a.fb=b.d5;}else{d=a.eY.d2.data;e=a.fA;a.fA=e+1|0;b=d[e];a.eJ=b;a.fb=b.d5;a.f9=null;}},K7=a=>{let b,c,d,e,f;IL(a);b=a.eJ;if
(b===null){b=new CQ;Y(b);S(b);}c=a.f9;if(c!==null)c.d5=b.d5;else{d=b.eT;e=a.eY.d2.data;f=d&(e.length-1|0);e[f]=e[f].d5;}a.eJ=null;a.fI=a.fI+1|0;b=a.eY;b.d7=b.d7+1|0;b.d1=b.d1-1|0;},Gs=H(C8),MN=a=>{HM(a);return a.eJ.ep;};
function H6(){BC.call(this);this.gX=null;}
let Jr=a=>{let b,c;b=(a.gX.c7()).ba();c=new Hf;c.hy=a;c.fN=b;return c;};
function IC(){let a=this;BC.call(a);a.gx=null;a.g9=0;}
let Hn=a=>{let b;b=new Iw;E9(b,a.gx,a.g9);return b;};
function Gf(){let a=this;F.call(a);a.ey=null;a.eS=null;a.fO=null;a.fq=0;a.fz=0;a.eL=null;}
let Me=(a,b,c,d,e)=>{a.eL=b;a.fz=b.d8;a.ey=c;a.eS=d;a.fq=e;},Fq=(a,b,c,d)=>{let e=new Gf();Me(e,a,b,c,d);return e;},Id=a=>{return a.ey===null?0:1;},E7=a=>{let b,c;Hh(a);b=a.ey;if(b===null){b=new Dy;Y(b);S(b);}c=b.gd;a.fO=b;a.eS=b;a.ey=b.ek;a.fq=a.fq+1|0;return c;},Hh=a=>{let b;if(a.fz>=a.eL.d8)return;b=new Dd;Y(b);S(b);},JF=H(),CQ=H(Bv);
function Hf(){let a=this;F.call(a);a.fN=null;a.hy=null;}
let MF=a=>{return a.fN.bb();},MG=a=>{return (a.fN.bc()).ep;},JV=a=>{a.fN.bC();};
function C7(){let a=this;F.call(a);a.gp=null;a.hi=0;a.fP=0;a.fL=null;a.eM=null;}
let E9=(a,b,c)=>{a.gp=b;a.hi=c;a.fP=b.d7;a.fL=!c?b.es:b.eu;},NU=(a,b)=>{let c=new C7();E9(c,a,b);return c;},BY=a=>{return a.fL===null?0:1;},Ha=a=>{let b;if(a.fP==a.gp.d7)return;b=new Dd;Y(b);S(b);},Io=a=>{let b;Ha(a);if(!BY(a)){b=new Dy;Y(b);S(b);}b=a.fL;a.eM=b;a.fL=!a.hi?b.eh:b.eb;},Ld=a=>{let b;if(a.eM===null){b=new CQ;Y(b);S(b);}Ha(a);KH(a.gp,a.eM);a.eM=null;a.fP=a.fP+1|0;},Iw=H(C7),Cp=a=>{Io(a);return a.eM.ep;},Dy=H(Bv);
function Fs(){F.call(this);this.eH=null;}
let JU=(a,b)=>{let c,d,e,f,g,h,i;if(!(b instanceof Fs))return 0;c=b;d=DY(a.eH.dy());e=DY(c.eH.dy());b=d;if(!EE(b,e))return 0;f=O(b);g=O(e);e=f;d=g;while(P(e)&&P(d)){h=Q(e);i=Q(d);b=DS(a.eH,h);f=DS(c.eH,i);if(!EE(b,f))return 0;}return 1;},Lt=a=>{let b,c,d;b=0;c=(a.eH.dy()).ba();while(c.bb()){d=c.bc();d=O(DS(a.eH,d));while(P(d)){b=b^HG(Q(d));}}return b;};
function Ic(){BC.call(this);this.hd=null;}
let Lu=a=>{let b;b=new HZ;Ej(b,a.hd);return b;};
function H9(){Cb.call(this);this.gl=null;}
let NA=a=>{let b,c;b=CG(a.gl);c=new H7;c.fW=b;return c;},Ka=a=>{return a.gl.f5.d1;};
function Ia(){Di.call(this);this.gy=null;}
let JR=a=>{return 1;},Mm=(a,b)=>{let c;if(!b)return a.gy;c=new BN;Y(c);S(c);},HZ=H(C8),Mn=a=>{HM(a);return a.eJ;};
function H7(){F.call(this);this.fW=null;}
let Nh=a=>{return BY(a.fW);},Je=a=>{return CH(a.fW);},HH=H(),IO=null,Fu=()=>{Fu=GX(HH);Jb();},Jb=()=>{let b,c;b=BE((Go()).data.length);c=b.data;IO=b;c[D7.eN]=1;c[DC.eN]=2;c[D5.eN]=3;};
function GD(){let a=this;Cb.call(a);a.f5=null;a.hb=0;}
let CG=a=>{let b;b=new Hl;E9(b,a.f5,a.hb);return b;},Hl=H(C7),CH=a=>{Io(a);return a.eM.eg;};
Ki([-1,"java",0,"lang"]);
DE([F,0,0,[],0,3,0,0,["D",G(Np),"C",M(Bg)],GL,0,F,[],3,3,0,0,0,Gg,0,F,[],3,3,0,0,0,GV,0,F,[GL,Gg],4,3,0,0,0,M8,0,F,[],4,3,0,0,0,Md,0,F,[],4,3,0,0,0,FE,0,F,[],0,3,0,0,0,Cz,0,FE,[],0,3,0,0,0,Bv,0,Cz,[],0,3,0,0,0,C5,0,Bv,[],0,3,0,0,0,BV,0,F,[],3,3,0,0,0,C2,0,F,[],3,3,0,0,0,Fj,0,F,[],3,3,0,0,0,BX,0,F,[BV,C2,Fj],0,3,0,0,0,FH,0,F,[BV],1,3,0,0,0,DF,0,FH,[C2],0,3,0,0,["D",G(Ji),"C",M(MC)],DR,0,F,[BV,Fj],0,0,0,0,["q",M(Fc),"g",G(T)],E4,0,F,[],3,3,0,0,0,Gp,0,DR,[E4],0,3,0,0,["g",G(L4),"q",M(M_)],MW,0,F,[],0,3,0,0,0,Nk,
0,F,[],0,3,0,0,0,JB,0,F,[],0,3,0,0,0,IJ,0,F,[],4,3,0,C$,0,NE,0,F,[],4,3,0,0,0,C3,0,F,[],3,3,0,0,0,H$,0,F,[C3],0,3,0,0,0,HX,0,F,[C2],0,3,0,0,0,Kj,0,F,[],4,3,0,0,0,Ni,0,F,[],4,3,0,0,0,E3,0,F,[],0,3,0,0,0,GZ,0,F,[],0,3,0,0,0,HS,0,F,[],3,3,0,0,0,IP,0,F,[HS],0,0,0,0,0,DM,0,Bv,[],0,3,0,0,0,BN,0,Bv,[],0,3,0,0,0,BD,0,F,[],0,3,0,0,0,B5,0,F,[],1,3,0,0,0,Bu,0,B5,[],0,3,0,0,["S",M(Mf),"cg",M(Nm),"bw",M(Is),"g",G(K_)],Br,0,B5,[],0,3,0,0,["S",M(Nw),"cg",M(MB),"bw",M(H8),"g",G(J_)],Bk,0,B5,[],0,3,0,0,["S",M(MX),"cg",M(L2),
"bw",M(Lz),"g",G(Nn)],GM,0,F,[],3,3,0,0,0,Dm,0,F,[GM],3,3,0,0,0,Cb,0,F,[Dm],1,3,0,0,["T",G(Bj),"J",M(BI)],Dx,0,F,[Dm],3,3,0,0,0,Ex,0,F,[Dx],3,3,0,0,0,B3,0,Cb,[Ex],1,3,0,0,["G",M(CB),"ba",G(O),"bD",Be(Kz),"C",M(EE)],Cm,0,F,[],3,3,0,0,0,Dp,0,F,[],3,3,0,0,0,DV,0,B3,[Cm,BV,Dp],0,3,0,0,["bE",M(Bl),"bx",G(E_),"G",M(J),"bD",Be(Mj),"D",G(MU)],Dw,0,F,[C2,BV],1,3,0,0,0]);
DE([C4,0,Dw,[],12,3,0,0,0,Fp,0,F,[],3,3,0,0,0,Ew,0,F,[Fp],3,3,0,0,0,FW,0,F,[Ew],0,3,0,0,["bd",Be(HI)],BZ,0,F,[Fp],3,3,0,0,0,HY,0,F,[BZ],0,3,0,0,["bd",Be(Mc)],H4,0,F,[BZ],0,3,0,0,["bd",Be(I3)],FY,0,F,[Ew],0,3,0,0,["bd",Be(GW)],Ie,0,F,[BZ],0,3,0,0,["bd",Be(K8)],HV,0,F,[BZ],0,3,0,0,["bd",Be(KA)],GC,0,F,[BZ],0,3,0,0,["bd",Be(Mr)],IG,0,F,[BZ],0,3,0,0,["bd",Be(Mx)],Hq,0,F,[BZ],0,3,0,0,["bd",Be(LA)],D1,0,F,[BZ],0,3,0,0,["bd",Be(J8)],Hp,0,D1,[],0,3,0,0,["bd",Be(Nz)],GK,0,F,[BZ],0,3,0,0,["bd",Be(Lf)],Dl,0,F,[BZ],3,3,
0,0,0,G2,0,F,[Dl],0,3,0,0,["bd",Be(NC)],Ht,0,F,[Dl],0,3,0,0,["bd",Be(IV)],Ga,0,F,[Dl],0,3,0,0,["bd",Be(Js)],Ih,0,F,[Dl],0,3,0,0,["bd",Be(ML)],Z,0,F,[Cm],0,3,0,0,["C",M(Fe),"D",G(Mp)],In,0,F,[],0,3,0,0,0,Ce,0,Bv,[],0,3,0,0,0,D8,0,F,[Dm],3,3,0,0,0,BC,0,Cb,[D8],1,3,0,0,["C",M(EM),"D",G(Jx)],FS,0,BC,[Cm,BV],1,3,0,0,0,HU,0,FS,[],0,0,0,0,0,Lg,0,F,[],0,3,0,0,0,Fr,0,BN,[],0,3,0,0,0,FF,0,F,[],3,3,0,0,0,ID,0,F,[FF],0,3,0,0,["bO",M(FX)],BF,"InterruptedException",1,Cz,[],0,3,0,0,0,BB,0,F,[],3,3,0,0,0,De,0,F,[],1,3,0,0,
["bi",G(NK),"dp",G(LX)],Ge,0,Cz,[],0,3,0,0,0,B_,0,F,[],3,3,0,0,0,G9,0,F,[B_],0,0,0,0,["bb",G(P),"bc",G(Q)],LB,0,F,[],4,3,0,0,0,Ku,0,F,[],4,3,0,0,0,CC,0,Bv,[],0,3,0,0,0,IM,0,Bv,[],0,3,0,0,0,Dd,0,Bv,[],0,3,0,0,0,DH,0,F,[],3,3,0,0,0,Du,0,F,[DH],1,3,0,0,["dm",G(KP)],C6,0,Du,[Cm,BV],0,3,0,0,["c_",M(K2),"cm",M(CW),"c7",G(M5),"cn",M(Ch),"T",G(D6),"dm",G(Ne),"bS",Be(W),"dn",M(JQ),"bx",G(Im)],G7,0,F,[DH],3,3,0,0,0,EU,0,C6,[G7],0,3,0,0,["c_",M(LU),"bS",Be(B8),"dm",G(IB),"dn",M(M6)],DQ,0,F,[],0,3,0,0,0,CM,0,BC,[Cm,BV],
0,3,0,0,["G",M(Bq),"J",M(BP),"T",G(CT),"ba",G(Bp),"bx",G(CK)]]);
DE([E6,0,F,[Dx,D8],3,3,0,0,0,EG,0,CM,[E6,Cm,BV],0,3,0,0,0,Bo,0,De,[],1,3,0,0,["bR",G(Bn),"bg",G(JI)],EY,0,Bo,[BB],0,3,0,0,["bf",G(LE),"g",G(KR),"C",M(I5)],NG,0,F,[],0,3,0,0,0,CE,0,Bo,[],1,3,0,0,["bg",G(Kc)],C1,0,CE,[],0,3,0,0,["g",G(K4)],Ik,0,F,[C3],0,0,0,0,["dt",Be(LW)],Lq,0,F,[],0,3,0,0,0,B4,0,Bo,[BB],1,3,0,0,["bf",G(E$),"g",G(I_),"C",M(FJ),"D",G(IS)],GB,0,C1,[],0,0,0,0,0,GA,0,CE,[],0,3,0,0,["bg",G(Ng),"g",G(Kv)],GN,0,CE,[],0,3,0,0,["g",G(KV),"bg",G(IX)],C9,0,De,[],1,3,0,0,["bi",G(JA),"bg",G(IQ),"C",M(Kd)],HQ,
0,C9,[BB],0,3,0,0,["bf",G(Na)],Ma,0,F,[],0,3,0,0,0,Gq,0,F,[C3],0,3,0,0,["dt",Be(Le)],CU,0,F,[],3,3,0,0,0,BS,0,Bo,[BB,CU],1,3,0,0,["dN",Be(MA),"bi",G(JY),"dp",G(M7),"C",M(M3),"D",G(I$)],F0,0,Bo,[BB,CU],0,3,0,0,["bf",G(MP),"dN",Be(JZ),"C",M(MS),"g",G(Ks)],Cd,0,Bo,[BB],1,3,0,0,0,HD,0,Cd,[BB],0,3,0,0,["bf",G(KB),"g",G(Nl)],Hr,0,Cd,[BB],0,3,0,0,["bf",G(Mq),"g",G(J4)],IE,0,Cd,[BB],0,3,0,0,["bf",G(NN),"g",G(I4)],IN,0,Cd,[BB],0,3,0,0,["bf",G(MZ),"g",G(Jh)],Ip,0,C9,[BB],0,3,0,0,["bf",G(JS)],Ee,0,Bo,[BB,CU],0,3,0,0,["bf",
G(NL),"dN",Be(LR),"g",G(Ll),"C",M(Jj)],Gz,0,B4,[],0,3,0,0,["ds",G(LG)],If,0,B4,[],0,3,0,0,["ds",G(J3)],IA,0,B4,[],0,3,0,0,["ds",G(KJ)],EJ,0,BC,[],1,0,0,0,0,F_,0,EJ,[],0,0,0,0,["ba",G(I7)],Ft,0,Du,[],1,0,0,0,0,F9,0,Ft,[],0,0,0,0,["c7",G(JP),"bx",G(LO),"cn",M(IT),"T",G(ND),"cm",M(KO)],Di,0,B3,[Dp],1,0,0,0,0,F$,0,Di,[],0,0,0,0,0,F7,0,F,[B_],0,0,0,0,["bb",G(J6),"bc",G(Lr),"bC",G(I0)],FU,0,F,[B_],3,3,0,0,0,F8,0,F,[FU],0,0,0,0,0,Iz,0,F,[C3],0,3,0,0,0,Ix,0,Bo,[BB,CU],0,3,0,0,["bf",G(Kp),"dN",Be(LJ),"g",G(Kt)],Ep,0,
Bo,[BB],0,3,0,0,["bi",G(MJ),"dp",G(M2),"bR",G(Mv),"bf",G(MV),"g",G(L1),"C",M(L0)],G$,0,Bo,[BB,CU],0,3,0,0,["bf",G(JW),"dN",Be(Ky),"g",G(M9)],Hu,0,Bo,[BB],0,3,0,0,["bi",G(Jt),"dp",G(Jp),"bR",G(M$),"bf",G(I2),"g",G(LF)],Er,0,B4,[],0,3,0,0,["bf",G(Lc),"ds",G(MD),"C",M(NB)],FV,0,B4,[],0,3,0,0,["bf",G(I8),"ds",G(Lx),"C",M(Lv)],GU,0,B3,[Dp,BV],0,0,0,0,["bE",M(IY),"bx",G(K$)],Gb,0,F,[],3,3,0,0,0,FC,0,F,[Gb,Cm],0,0,0,0,0,Db,0,FC,[],0,0,0,0,0]);
DE([ET,0,Db,[],4,0,0,0,0,F4,0,F,[C3],0,0,0,0,["dt",Be(Mk)],F6,0,B3,[],0,0,0,0,["bE",M(Lh),"bx",G(Lb)],Cj,0,F,[],0,3,0,0,["C",M(Dr),"D",G(HG)],Hx,0,BC,[],0,3,0,0,["G",M(BK),"J",M(Cl),"ba",G(CA),"bx",G(KU)],Fx,0,BS,[],0,3,0,0,["dy",G(JJ),"dC",G(Nj),"dE",G(Jk),"bf",G(LQ),"dA",G(Jv),"g",G(I1)],H0,0,F,[],3,3,0,0,0,Kr,0,F,[H0,BV],0,3,0,0,0,E2,0,B3,[],1,3,0,0,["bD",Be(Ig)],Gh,0,F,[Dm],3,3,0,0,0,H_,0,F,[Gh,Dx],3,3,0,0,0,Fy,0,E2,[H_],0,3,0,0,["bx",G(MY)],GG,0,BS,[],0,3,0,0,["dy",G(MM),"dC",G(LL),"dE",G(Kq),"bf",G(NI),
"dA",G(J1),"g",G(Mi)],Ef,0,BS,[],0,3,0,0,["dC",G(LC),"dy",G(Kx),"dE",G(Ms),"bf",G(MI),"dA",G(L$),"g",G(J0)],HL,0,BS,[],0,3,0,0,["dC",G(IR),"dy",G(Jn),"dE",G(I9),"bf",G(L3),"dA",G(LY),"g",G(Nd)],Hw,0,BS,[],0,3,0,0,["dC",G(J$),"dy",G(Ln),"dE",G(KF),"bf",G(KX),"bi",G(NO),"dp",G(JD),"dA",G(JH),"g",G(Nb)],Cu,0,Dw,[],12,3,0,0,0,GH,0,F,[FF],0,0,0,0,["bO",M(J7)],Fm,0,F,[],0,0,0,0,0,It,0,BC,[],0,0,0,0,["ba",G(IW)],LH,0,F,[],4,3,0,0,0,Il,0,F,[],3,3,0,0,0,GR,0,F,[Il],3,3,0,0,0,H3,0,F,[],3,3,0,0,0,Fg,0,F,[GR,H3],1,3,0,
0,0,EQ,0,Fg,[],0,3,0,0,0,EN,0,EQ,[E4],0,3,0,0,0,E1,0,EN,[],1,3,0,0,0,Gx,0,E1,[],0,3,0,0,0,Kl,0,F,[C2],1,3,0,0,0,C8,0,F,[],0,0,0,0,["bb",G(GP),"bC",G(K7)],Gs,0,C8,[B_],0,0,0,0,["bc",G(MN)],H6,0,BC,[],0,0,0,0,["ba",G(Jr)],IC,0,BC,[E6],0,0,0,0,["ba",G(Hn)],Gf,0,F,[FU],0,0,0,0,0,JF,0,F,[],0,3,0,0,0,CQ,0,Bv,[],0,3,0,0,0,Hf,0,F,[B_],0,0,0,0,["bb",G(MF),"bc",G(MG),"bC",G(JV)],C7,0,F,[],0,0,0,0,["bb",G(BY),"bC",G(Ld)],Iw,0,C7,[B_],0,0,0,0,["bc",G(Cp)],Dy,0,Bv,[],0,3,0,0,0,Fs,0,F,[],0,3,0,0,["C",M(JU),"D",G(Lt)],Ic,
0,BC,[],0,0,0,0,["ba",G(Lu)],H9,0,Cb,[],0,0,0,0,["ba",G(NA),"bx",G(Ka)],Ia,0,Di,[Dp],0,0,0,0,["bx",G(JR),"bE",M(Mm)],HZ,0,C8,[B_],0,0,0,0,["bc",G(Mn)],H7,0,F,[B_],0,0,0,0,["bb",G(Nh),"bc",G(Je)],HH,0,F,[],32,0,0,Fu,0,GD,0,Cb,[Dx],0,0,0,0,0,Hl,0,C7,[B_],0,0,0,0,0]);
let L_=Cx(Ho),Ml=Cx(GF);
JL(["0","<java_object>@","null","","Cell","s "," ",",","row","column","block","HiddenSingle","Hidden Single","DirectPointing","Direct Pointing","DirectHiddenPair","Direct Hidden Pair","NakedSingle","Naked Single","DirectHiddenTriplet","Direct Hidden Triplet","PointingClaiming","Pointing & Claiming","NakedPair","Naked Pair","XWing","X-Wing","HiddenPair","Hidden Pair","NakedTriplet","Naked Triplet","Swordfish","HiddenTriplet","Hidden Triplet","XYWing","XY-Wing","XYZWing","XYZ-Wing","UniqueLoop","Unique Rectangle / Loop",
"NakedQuad","Naked Quad","Jellyfish","HiddenQuad","Hidden Quad","BivalueUniversalGrave","Bivalue Universal Grave","AlignedPairExclusion","Aligned Pair Exclusion","ForcingChainCycle","Forcing Chains & Cycles","AlignedTripletExclusion","Aligned Triplet Exclusion","NishioForcingChain","Nishio Forcing Chains","MultipleForcingChain","Multiple Forcing Chains","DynamicForcingChain","Dynamic Forcing Chains","DynamicForcingChainPlus","Dynamic Forcing Chains (+)","NestedForcingChain","Nested Forcing Chains","the cell can contain only one value",
"only remaining possible value in the cell","Parent not found",": ","\n","\tat ","Caused by: ","Y-Chain","X-Chain","More than one \"","\" in a ","DoubleValue.html","The sudoku has been solved","SudokuSolved.html","Sudoku is not valid","TooFewCells.html",", ","Sudoku has multiple solutions","TooFewValues.html","The Sudoku has no solution","NoSolution.html","MissingCandidates.html","bitIndex: ","fromIndex: ","countOnes < 0","countBits < 0","countOnes > countBits","countBits > 64","Aligned Quad Exclusion","Aligned Set (",
") Exclusion","Loop","Rectangle","Unique "," type "," on ","Solution"," on value ","BUG type 1: ","BUG type 2: ","BUG type 4: ","BUG type 3: ","Claiming","Pointing","Block X-Wing"," in "," and ","s and ","s","Pair","Triplet","Quad","Naked ","Cells [...]","Direct Claiming"," of ","Hidden ","Direct Hidden ","Cell Forcing Chains"," off"," on"," ==> ","Nishio Forcing Chain: "," both on & off","Double Forcing Chain: "," on & off ==> ","Contradiction Forcing Chain: ","Region Forcing Chains","Bidirectional Cycle",
"Bidirectional Y-Cycle","Bidirectional X-Cycle","Generalized X-Wing","Forcing Chain","Forcing Y-Chain","Forcing X-Chain","Turbot Fish","HiddenBlock","HiddenRow","HiddenColumn","Advanced"]);
BX.prototype.toString=function(){return D9(this);};
BX.prototype.valueOf=BX.prototype.toString;F.prototype.toString=function(){return D9(Mh(this));};
F.prototype.__teavm_class__=function(){return Ns(this);};
let C=IZ(K1);
C.javaException=Lp;
let NT=Symbol('jsoClass');
(()=>{let c;})();
export{C as main,D as rate};