// Writes src/sudoku/defaultsDoubleDynamicDragonPuzzleStockData.ts - the stock behind "Dynamic Dragon only uses
// defaults" (Generate Puzzle menu) - from the allon3 hunts' hits (ddd-settings-hunt.ts, MODE=allon3):
//  - independent: the INDEPENDENT=1 run's stuck positions (Sudoku.Coach states) and the INDEPENDENT=1 START=1
//    run's 81-char strings (each the stuck position itself, candidates autofilled);
//  - non-independent: the plain allon3 run's stuck positions.
// Re-run whenever those hunts find more:
//   npx rolldown dragon-research/build-defaults-ddd-stock.ts --format esm --platform node -o <tmp>/build.mjs && node <tmp>/build.mjs
import fs from 'fs'

const ROOT = 'C:/Git/sudoku-solver/frontend/'
const DIR = ROOT + 'dragon-research/data/'
const OUT = ROOT + 'src/sudoku/defaultsDoubleDynamicDragonPuzzleStockData.ts'

const jsonl = (f: string): any[] =>
  fs.existsSync(DIR + f) ? fs.readFileSync(DIR + f, 'utf8').trim().split('\n').filter(Boolean).map((l) => JSON.parse(l)) : []
const unique = (xs: string[]) => [...new Set(xs)]

const independentStates = unique(jsonl('ddd-allon3-hits-independent.jsonl').map((h) => h.firstStuck))
const independentStrings = unique(jsonl('ddd-allon3-hits-independent-start.jsonl').map((h) => h.puzzle))
const nonIndependentStates = unique(jsonl('ddd-allon3-hits.jsonl').map((h) => h.firstStuck))

const list = (xs: string[]) => xs.map((x) => `  '${x}',`).join('\n')
fs.writeFileSync(
  OUT,
  `/** "Dynamic Dragon only uses defaults" Double Dynamic Dragon Colouring
 * positions (Generate Puzzle menu), served by dynamicDragonPuzzleStock.ts's
 * pickStockDefaultsDoubleDynamicDragonPuzzle. Each was verified through the
 * app's own engine (buildTechniqueInstances) with every standalone technique
 * ON except Sue-de-Coq (Short AIC, Short Single-Digit AIC, Generic AIC, every
 * fish, ALS-xz, Double plain Dragon), Dynamic Dragon limited to
 * DEFAULT_RULE3_TECHNIQUES, "Max techniques per step" = 3, the rest at
 * defaults: at the position nothing applies until Double Dynamic Dragon
 * Colouring is turned on, then only Double Dynamic rows do, and solving on
 * (simplest row first) finishes with no guessing, every step checked against
 * the solution. Turning standalone techniques off only removes rows, so the
 * positions hold whatever the player has enabled.
 *
 * Entries are either Sudoku.Coach states (a mid-solve stuck position, served
 * as is) or 81-char strings (the stuck position itself, every filled cell a
 * given, candidates autofilled). Generated by
 * dragon-research/build-defaults-ddd-stock.ts - don't edit by hand. */

/** At every stuck point an independent Double Dynamic row (its second Medusa
 * starts on no candidate the first Dragon coloured) was what got applied. */
export const DEFAULTS_DOUBLE_DYNAMIC_DRAGON_INDEPENDENT_STOCK: readonly string[] = [
${list([...independentStates, ...independentStrings])}
]

/** The same without the independence rule. */
export const DEFAULTS_DOUBLE_DYNAMIC_DRAGON_NON_INDEPENDENT_STOCK: readonly string[] = [
${list(nonIndependentStates)}
]
`,
)
console.log(`independent: ${independentStates.length} states + ${independentStrings.length} strings; non-independent: ${nonIndependentStates.length} states`)
